# fr3打印二维码请求子系统地址
url:
  # 审核登簿UI地址
  register-ui: http://192.168.50.78:8671/realestate-register-ui
  storage: http://200.1.1.168:8019/storage
# （南通）发票号财务登记费用户信息
finance:
  djfMap:
    zhb:
      # 网点id
      wdid: 网点id
      # 财务用户id
      czy: 1962
      # 财务用户name
      czym: YUANW
  # 银行名称
  yhmcList:

printType:
  nantong: 有房无房证明,有房无房证明（企业）,权属证明,抵押证明,不为申请人所有证明,已出售证明,无不动产登记资料证明,贷款证明,座落变更证明（原座落）,座落变更证明（现座落）,其他证明
  heifei: 房产证明,不动产详情,不动产附表,抵押物清单
  standard: 有房无房证明,权属证明
# 此地方需求更改大，直接全部可配置，避免代码来回改动
nantong:
  # 综合查询证明模板名称
  zhcxzmmb:
    # 有房证明
    yfzm: yfzm.fr3
    # 无房证明
    wfzm: wfzm.fr3
    # 有房证明（企业）
    yfzmqy: yfzmqy.fr3
    # 无房证明（企业）
    wfzmqy: wfzmqy.fr3
    # 不为申请人所有证明
    bwsqrsyzm:  bwsqrsyzm.fr3
    # 已出售证明
    ycszm:  ycszm.fr3
    # 无不动产登记资料证明
    wbdcdjzlzm:  wbdcdjzlzm.fr3
    # 贷款证明
    dkzm:  dkzm.fr3
    # 座落变更证明（原座落）
    zlbgzmyzl:  zlbgzmyzl.fr3
    # 座落变更证明（现座落）
    zlbgzmxzl:  zlbgzmxzl.fr3
    # 其他证明
    qtzm:  qtzm.fr3

  # 海门迁户口证明模板名称
  haimen:
    qhkzm:
      # 有房证明
      yfzm: qhkzmyfzm.fr3
      # 无房证明
      wfzm: qhkzmwfzm.fr3

  # 证明内容显示部分1
  zmnr1:
    # 不为申请人所有证明
    bwsqrsyzm:  本次查询仅根据查询申请人提供的身份证及不动产坐落进行查询，查询范围为：南通市市区（限崇川区、港闸区）国有土地范围内的不动产登记簿。
    # 已出售证明
    ycszm:  本次查询仅根据查询申请人提供的身份证及不动产坐落进行查询，查询范围为：南通市市区（限崇川区、港闸区）国有土地范围内的不动产登记簿。
    # 无不动产登记资料证明
    wbdcdjzlzm:  本次查询仅根据查询申请人提供的身份证及不动产坐落进行查询，查询范围为：南通市市区（限崇川区、港闸区）国有土地范围内的不动产登记簿。
    # 贷款证明
    dkzm:  本次查询仅根据查询申请人提供的身份证及不动产坐落进行查询，查询范围为：南通市市区（限崇川区、港闸区）国有土地范围内的不动产登记簿。
    # 座落变更证明（原座落）
    zlbgzmyzl:  本次查询仅根据查询申请人提供的身份证及不动产坐落进行查询，查询范围为：南通市市区（限崇川区、港闸区）国有土地范围内的不动产登记簿。
    # 座落变更证明（现座落）
    zlbgzmxzl:  本次查询仅根据查询申请人提供的身份证及不动产坐落进行查询，查询范围为：南通市市区（限崇川区、港闸区）国有土地范围内的不动产登记簿。
    # 其他证明
    qtzm:  本次查询仅根据查询申请人提供的身份证及不动产坐落进行查询，查询范围为：南通市市区（限崇川区、港闸区）国有土地范围内的不动产登记簿。

  # 证明内容显示部分2
  zmnr2:
    # 不为申请人所有证明
    bwsqrsyzm:  在上述查询时点，查阅不动产登记簿：
    # 已出售证明
    ycszm:  在上述查询时点，查阅不动产登记簿：
    # 无不动产登记资料证明
    wbdcdjzlzm:  在上述查询时点，查阅不动产登记簿：
    # 贷款证明
    dkzm:  在上述查询时点，查阅不动产登记簿：
    # 座落变更证明（原座落）
    zlbgzmyzl:  在上述查询时点，查阅不动产登记簿：
    # 座落变更证明（现座落）
    zlbgzmxzl:  在上述查询时点，查阅不动产登记簿：
    # 其他证明
    qtzm:  在上述查询时点，查阅不动产登记簿：

# 附件下载
fjxz:
  # ftp服务器地址
  ip: 192.168.10.84
  # ftp服务器端口号
  port: 21
  # ftp用户名
  user: gt
  # ftp密码
  password: gtis
  # 查封附件路径
  cffjpath:
  # 土地房屋附件路径
  tdfwfjpath:

# 抵押统计查询，需要排除的流程定义ID，多个以英文逗号分隔
dyatj.except.gzldyid: r5wJBF4dZbPFXbzf

# 受理查询判断是否需要验证同名权利人证件号为空或不规则的情况,不配置默认为验证(true)
dycx.valid.qlrzjh: false

# 标准版综合查询配置项 （2020-03-02新增）
standard:
  ## 查询项配置
  search:
    ### 查询时，如果只输入权利人名称，则通过配置控制证件号是否必填
    ### 0 不需要必填； 1 需要必填
    zjhsfbt: 0
  ## 证明项配置
  prove:
    ### 出具有房无房时，姓名必填，通过配置控制证件号是否必填
    ### 0 不需要必填； 1 需要必填
    zjhsfbt: 0

  ## 档案附件地址
  archiveUrl: http://192.168.50.181:8064/archive/gateway!originalInfoBySlbh.action?slbh=

changzhou:
  fph:
    # 项目类别对比，1 非税收入 9 结算凭证 配置对应类型的 sfxmdm
    xmlbdb: {1: '1,2,3,4,5', 9: '6,11,12,16'}

# 盐城综合查询查询目的（逗号分隔）
yancheng.zhcx.cxmd: 契税缴纳,学生入学

# 盐城历史关系权利信息展示详细内容，默认不生成 xsxx（显示信息）字段

yancheng.lsgx:
  xsxx: true
  syg: true

# 征迁注销申请审核通过后在登记发起的注销流程工作流定义ID
yancheng.zq.djzxlc: WR3msbJr8P335c8H
# 征迁创建的注销流程允许被领取的角色编码，英文逗号间隔
yancheng.zq.role: sl,sz

# 综合查询权利类型筛选配置
zhcx.qllx.sxpz: 土地 1,2,3,5,7,23 checked;房屋 4,6,8,24,25,26,94 checked;海域 15,17;林权 10,11,12;预告 96;经营权 9,35

#省级共享接口配置
sjgx.dmxx.xzqdm: 320900
sjgx.dmxx.dmmc: 盐城市
#省级共享接口目录根据流程配置,sfhc
sjgx.jkml.iwiSMbTcycBSr2Di: sjswyxzm

# 盐城网上业务台账，下拉框内容
config:
  wsyw:
    gzldyids: jsEKwceZQswjPAyx,hfQ236Q2XSQZtRjS
    ##是否进行权籍管理过滤
  qjgldmfilter: true

##权籍管理代码过滤对照，key为用户组织机构代码，value为需要查询的权籍管理代码，多个用英文逗号隔开，不配对照默认组织机构代码即为权籍管理代码,阿波罗配置格式为{'320400':'320402,320404','320412':'32012,320499'}
qjgldmfilter:
  zzjgQjgldm: '{"340104":"340100,340124","340111":"340100,340124"}'

gzltj:
  # 工作量统计的节点测试数统计方式 # realCount:多次审核算一次 count:每次审核一次算一次
  jdcstjfs: realCount
  # 统计的节点的名称和柱状图颜色
  jdmc: "{受理: '#5470C6',初审: '#EE6666',复审: '#FB8452',核定: '#FAC758',缮证: '#91CC75',其他: '#73C0DE'}"


# 原 config-ui 配置迁移至 inquiry-ui
# 印制号人员过滤角色配置 （设置印制号展示人员时候需要过滤的角色编）
zsyzh:
  roles: cfsl

# 下载日志配置
#  applyName: F:/hefei/ #本机测试数据
xzrzConfig:
  version: -3.1.0
  configs:
    - host: 192.168.2.206
      port: 22
      username: root
      password: abc123!@#
      path: /home/realestate/hefei/
      applyName: /home/hefei/
      name: 合肥登记UI应用
    - host: 192.168.0.60
      port: 22
      username: root
      password: gtis@123
      path: /home/
      applyName: /home/guotu/
      name: 国图登记服务应用
    - host: 192.168.2.125
      port: 22
      username: root
      password: redhat
      path: /home/
      applyName: /home/redhat/
      name: 小红帽登记服务应用
#综合查询  查询限制状态信息的 自定义查询的cxdh
zhcx.xzzt.cxdhmap: "{'cf':'cfxx','sd':'sd','yg':'ygbhdy','dyi':'dyi','jz':'jz','ydy':'ydy'}"




