info:
  name: ${spring.application.name}
  component: inquiry-ui application

app:
  center: http://192.168.2.70:8000/eureka/
  oauth: http://192.168.2.70:8030/account
  security:
    moduleAuthPath: http://account/account
    # 开放权限：静态资源、打印接口、工作量统计接口、发票号
    ignores: /image/**,/css/**,/js/**,/webjars/**,/static/print/**,/static/printModel/**,/rest/v1.0/print/**,/gzltj/**,/log/openFr3/**,/realestate-register/rest/v1.0/print/**,/rest/v1.0/fph/dy/xml,/rest/v1.0/changzhou/fph/dy/xml/**
    authorities:
      permitAll: /index2
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**,/index
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated: true
    resources:
      authenticated: /realestate-inquiry-ui/**
  services:
    realestate-config: realestate-config-yan
#    certificate-app: certificate-app-yan
#    accept-app: accept-app3
#    inquiry-app: inquiry-app-yan
#    init-app: init-app-yan
#    register-ui-app: register-ui-yan
#    register-app: register-app-yan
#    config-app: config-app-zxy
html:
#  parversion: standard
  version: standard

spring:
  rabbitmq:
    host: 192.168.2.72
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 127.0.0.1
  profiles:
    include: config
  messages:
    basename: conf/message/messages, conf/message/errors
  mvc:
    static-path-pattern: /**
  thymeleaf:
    prefix: classpath:/view/
    mode: LEGACYHTML5
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB


management:
  security:
    enabled: true
  context-path:

endpoints:
  enabled: true
  shutdown:
    enabled: true

server:
  port: ${port:8598}
  context-path: /realestate-inquiry-ui
  max-http-header-size: 10485760
  tomcat:
    max-http-post-size: -1
logging:
  level:
    org.springframework: info
    cn.gtmap.gtc.plugins: DEBUG

# 打印fr3文件保存服务器路径
print:
  path: C:\GTIS\print\
# 综合小屏展示
zhxp:
  dqzxmc: 包河区不动产登记中心

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
job.admin.addresses: http://127.0.0.1:8080/xxl-job-admin
### xxl-job, access token
### 执行器通讯TOKEN [选填]：非空时启用；
#job.accessToken=default_token
job.accessToken:
### xxl-job executor appname
### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#job.executor.appname= HelloRunner
job.executor.appname: job-executor123
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
job.executor.address:
### xxl-job executor server-info
### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
job.executor.ip:
### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
job.executor.port: 9999
### xxl-job executor log-path
### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
job.executor.logpath: /data/applogs/xxl-job/jobhandler
### xxl-job executor log-retention-days
### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
job.executor.logretentiondays: 30
