info:
  name: ${spring.application.name}
  component: Etl Application

app:
  center: http://192.168.2.99:8000/eureka/
  oauth: http://192.168.2.99:8002/account
  security:
    moduleAuthPath: http://account/account
    ignores: /index/**,/image/**,/css/**,/js/**,/webjars/**,/realestate-etl/rest/v1.0/wwsq/**,/realestate-etl/wwsq/fjxx/download,/realestate-etl/rest/v1.0/old/system/**
    authorities:
      permitAll: /index2
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**,/index
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated : true
    resources:
      authenticated: /resource/**,/realestate-etl/rest/v1.0/**
  services:
#    etl-app: etl-app
#    exchange-app: exchange-app0


spring:
  rabbitmq:
    host: 192.168.0.60
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 192.168.0.60
  datasource:
#    hlw:
#      url: jdbc:oracle:thin:@192.168.0.19:1521/orcl
#      username: bdcdj_gxsj_gs
#      password: gtis
    hlw:
      url: jdbc:oracle:thin:@192.168.2.86:1521/orcl
      username: bdcdj_hefei
      password: gtis
    exchange:
      url: jdbc:oracle:thin:@192.168.2.86:1521/orcl
      username: bdcdj_hefei
      password: gtis
    td:
      url: jdbc:oracle:thin:@192.168.2.86:1521/orcl
      username: bdcdj_hefei
      password: gtis
    fcjy:
      password: gtis
      url: jdbc:oracle:thin:@192.168.2.86:1521/orcl
      username: bdcdj_hefei
  messages:
    basename: conf/message/messages
  mvc:
    static-path-pattern: /realestate-etl/**

sftp:
  host: 192.168.2.125 # 服务器ip
  port: 22 # ssh端口
  username: root # 用户名
  password: abc123!@# # 密码
  # 连接池参数
  pool:
    max-total: 50
    max-idle: 50
    min-idle: 10

server:
  port: ${port:8800}

logging:
  level:
    org.springframework: WARN
    cn.gtmap.gtc.plugins: DEBUG
    cn.gtmap.realestate.etl.core.mapper: DEBUG

print.path: C:\GTIS\print\


wwsq.fjxx.bcfs: ftp
wwsq.ftp.ip: 192.168.2.86
wwsq.ftp.username: FtpAdmin
wwsq.ftp.password: Gtmap123
wwsq.ftp.port: 21
wwsq.ftp.ftpFilePath: /test/

##共享外网创建定时任务
##定时任务是否开启,true开启
gx.wwsqcj.enable: false
##定时任务表达式（默认半小时扫描一次）
gx.wwsqcj.cron: 0 0/30 * * * ?
##定时任务一次创建数量（默认100件,最大数量1000）
gx.wwsqcj.cjsl: 100

# 打印访问的ip地址
url.print-ip: http://127.0.0.1:8800
