
package cn.gtmap.realestate.exchange.util.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JrrzServiceService", targetNamespace = "http://loushang.ws", wsdlLocation = "http://10.0.0.6:81/realestate-supervise-server/services/jrrzsb?wsdl")
public class JrrzServiceService
    extends Service
{

    private final static URL JRRZSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException JRRZSERVICESERVICE_EXCEPTION;
    private final static QName JRRZSERVICESERVICE_QNAME = new QName("http://loushang.ws", "JrrzServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.0.6:81/realestate-supervise-server/services/jrrzsb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JRRZSERVICESERVICE_WSDL_LOCATION = url;
        JRRZSERVICESERVICE_EXCEPTION = e;
    }

    public JrrzServiceService() {
        super(__getWsdlLocation(), JRRZSERVICESERVICE_QNAME);
    }

    public JrrzServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JRRZSERVICESERVICE_QNAME, features);
    }

    public JrrzServiceService(URL wsdlLocation) {
        super(wsdlLocation, JRRZSERVICESERVICE_QNAME);
    }

    public JrrzServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JRRZSERVICESERVICE_QNAME, features);
    }

    public JrrzServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JrrzServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JrrzService
     */
    @WebEndpoint(name = "JrrzServicePort")
    public JrrzService getJrrzServicePort() {
        return super.getPort(new QName("http://loushang.ws", "JrrzServicePort"), JrrzService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JrrzService
     */
    @WebEndpoint(name = "JrrzServicePort")
    public JrrzService getJrrzServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://loushang.ws", "JrrzServicePort"), JrrzService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JRRZSERVICESERVICE_EXCEPTION!= null) {
            throw JRRZSERVICESERVICE_EXCEPTION;
        }
        return JRRZSERVICESERVICE_WSDL_LOCATION;
    }

}
