info:
  name: ${spring.application.name}
  component: Realestate Config Application

app:
  center: http://192.168.2.70:8000/eureka/
  oauth: http://192.168.2.70:8030/account
  security:
    moduleAuthPath: http://account/account
    ignores: /image/**,/css/**,/js/**,/webjars/**,/realestate-config/rest/v1.0/dysjZbPz/print
    authorities:
      permitAll: /index2
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**,/index
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated : true
    resources:
      hasScope('realestate_config_scope'): /realestate-config/**

spring:
  rabbitmq:
    host: 192.168.2.72
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 192.168.2.72
  datasource:
      url: jdbc:oracle:thin:@192.168.2.111:1521/orcl
      username: bdcdj_pz
      password: WAZyOcKhvgDjnBbP0C70W3jkWKgpudwUsLH0ojka0XYZVrKr6bRgWyaPtoFAdJr1m025jullQJj0Q7h3JdJLVQ==
      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIkhcbmyW8IgYViVU/4dKr+FUy0P9mSYhYLIgtlf2arzKI0ohb6/H0aUf4zWsW+GSRwECGmQbSKzOplzfeSELqUCAwEAAQ==
  profiles:
      include: config  #引入配置文件 application-config.yml
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
#new--
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    from: 3024059395@qq.com
    host: smtp.qq.com
    password: Vivad0ADDA
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    username: 3024059395@qq.com
#new--
#  mvc:
#    servlet:
#      load-on-startup: 0
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/static/

#new--

management:
  security:
    enabled: true
  context-path:
#new--
  health:
    mail:
      enabled: false
#  server:
#    base-path: /actuator
#new--

endpoints:
  enabled: true
  shutdown:
    enabled: true

server:
  port: ${port:8557}
#new--
#  servlet:
#    context-path: /xxl-job-admin
#new--

logging:
  level:
    org.springframework: WARN
    cn.gtmap.gtc.plugins: DEBUG
    cn.gtmap.realestate.config: DEBUG

#new--
xxl:
  job:
    accessToken: ''
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
#new--