config:
  # 是否从数据库加载配置项 false:否 true:是
  loadingConfigFlag: false
  # 印制号领取方式：设置印制号不同的地区对应的领取方式
  yzhlqfs:
    ## 领取方式：0 按照部门领取 ； 1 按照人员领取  2：默认直接按照区县代码领取
    ## -----测试用例，正式部署需要重新配置----- ##
    ##合肥市
    340100: 2
    ##市辖区
    340101: 2
    ##瑶海区
    340102: 2
    ##庐阳区
    340103: 2
    ##蜀山区
    340104: 2
    ##包河区
    340111: 2
    ##长丰县
    340121: 2
    ##肥东县
    340122: 2
    ##肥西县
    340123: 2
    ##庐江县
    340124: 2
    ##合肥高新技术产业开发区
    340171: 2
    ##合肥经济技术开发区
    340172: 2
    ##合肥新站高新技术产业开发区
    340173: 2
    ##巢湖市
    340181: 2

  # 发票号领取方式：设置发票号不同的地区对应的领取方式
  fphlqfs:
    ## 领取方式：0 按照部门领取 ； 1 按照人员领取  2：默认直接按照区县代码领取
    ## -----测试用例，正式部署需要重新配置----- ##
    ##合肥市
    340100: 2
    ##市辖区
    340101: 2
    ##瑶海区
    340102: 2
    ##庐阳区
    340103: 2
    ##蜀山区
    340104: 2
    ##包河区
    340111: 2
    ##长丰县
    340121: 2
    ##肥东县
    340122: 2
    ##肥西县
    340123: 2
    ##庐江县
    340124: 2
    ##合肥高新技术产业开发区
    340171: 2
    ##合肥经济技术开发区
    340172: 2
    ##合肥新站高新技术产业开发区
    340173: 2
    ##巢湖市
    340181: 2

### xxl-job, access token
### 调度中心通讯TOKEN [选填]：非空时启用；
#xxl.job.accessToken=default_token
#xxl.job.accessToken=

### xxl-job, i18n (default is zh_CN, and you can choose "zh_CN", "zh_TC" and "en")
### 调度中心国际化配置 [必填]： 默认为 "zh_CN"/中文简体, 可选范围为 "zh_CN"/中文简体, "zh_TC"/中文繁体 and "en"/英文；
xxl.job.i18n=zh_CN

## xxl-job, triggerpool max size
## 调度线程池最大线程配置【必填】
xxl.job.triggerpool.fast.max=200
xxl.job.triggerpool.slow.max=100

### xxl-job, log retention days
### 调度中心日志表数据保存天数 [必填]：过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能；
xxl.job.logretentiondays=30