config:
  # 是否从数据库加载配置项 false:否 true:是
  loadingConfigFlag: false
  # 印制号领取方式：设置印制号不同的地区对应的领取方式
  yzhlqfs:
    ## 领取方式：0 按照部门领取 ； 1 按照人员领取  2：默认直接按照区县代码领取
    ## -----测试用例，正式部署需要重新配置----- ##
    ##合肥市
    340100: 2
    ##市辖区
    340101: 2
    ##瑶海区
    340102: 2
    ##庐阳区
    340103: 2
    ##蜀山区
    340104: 2
    ##包河区
    340111: 2
    ##长丰县
    340121: 2
    ##肥东县
    340122: 2
    ##肥西县
    340123: 2
    ##庐江县
    340124: 2
    ##合肥高新技术产业开发区
    340171: 2
    ##合肥经济技术开发区
    340172: 2
    ##合肥新站高新技术产业开发区
    340173: 2
    ##巢湖市
    340181: 2

  # 发票号领取方式：设置发票号不同的地区对应的领取方式
  fphlqfs:
    ## 领取方式：0 按照部门领取 ； 1 按照人员领取  2：默认直接按照区县代码领取
    ## -----测试用例，正式部署需要重新配置----- ##
    ##合肥市
    340100: 2
    ##市辖区
    340101: 2
    ##瑶海区
    340102: 2
    ##庐阳区
    340103: 2
    ##蜀山区
    340104: 2
    ##包河区
    340111: 2
    ##长丰县
    340121: 2
    ##肥东县
    340122: 2
    ##肥西县
    340123: 2
    ##庐江县
    340124: 2
    ##合肥高新技术产业开发区
    340171: 2
    ##合肥经济技术开发区
    340172: 2
    ##合肥新站高新技术产业开发区
    340173: 2
    ##巢湖市
    340181: 2

spring:
  mail:
    from: 3024059395@qq.com
    host: smtp.qq.com
    password: Vivad0ADDA
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    username: 3024059395@qq.com
xxl:
  job:
    accessToken: ''
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
