info:
  name: ${spring.application.name}
  component: Realestate Config Application

app:
  center: http://192.168.2.99:8000/eureka/
  oauth: http://192.168.2.99:8002/account
  security:
    moduleAuthPath: http://account/account
    ignores: /image/**,/css/**,/js/**,/webjars/**,/realestate-config/rest/v1.0/dysjZbPz/print
    authorities:
      permitAll: /index2
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**,/index
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated : true
    resources:
      hasScope('realestate_config_scope'): /realestate-config/**

spring:
  rabbitmq:
    host: 192.168.0.60
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 192.168.0.60
  datasource:
      url: jdbc:oracle:thin:@192.168.2.86:1521/orcl
      username: bdcdj_hefei
      password: e/lWYHJj7d9rXmgsItIxLw2oWP4XasfqoDXA0AKNYHgeSJQK8IKgU8/+ia1ax4mr9ki4QZbrQrCW9WMkHDOPAA==
      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK8ev+xi3qANIZpQGhndeKtc2EOlsPd48VIhphnl3OoOKqynJuQo7qZrJekk8iqXHgvze3bnFrFyTtf3vxGIamsCAwEAAQ==
  profiles:
      include: config  #引入配置文件 application-config.yml
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    from: 3024059395@qq.com
    host: smtp.qq.com
    password: Vivad0ADDA
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    username: 3024059395@qq.com
management:
  security:
    enabled: true
  context-path:
  health:
    mail:
      enabled: false
endpoints:
  enabled: true
  shutdown:
    enabled: true

server:
  port: ${port:8557}

logging:
  level:
    org.springframework: WARN
    cn.gtmap.gtc.plugins: DEBUG
    cn.gtmap.realestate.config: DEBUG

xxl:
  job:
    accessToken: ''
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100

