accept:
#购物车页面信息的展示与隐藏，默认隐藏，true为展示
  yxbdcdyKgs:
    qllx: true
    sfzf: true
  #打印模板是否展示预览界面，true 不展示
  hidemodel: false
  qlrdlr:
    lcbs: FtE2swQGKKi3cekC
  #特殊流程
  lcbs:
    #预转现以及预告预抵押合并变更、转移（工作流定义id,多个用英文逗号隔开)
    yzx: Dz26PknGSPnTwSbr,enHCmXZQTGrC7m8A,dKKDi78sW852Y7N7,r5wJBF4dZbPFXbzf
    #带抵押(原产权存在抵押,需要注销原抵押生成新抵押)
    withdy: ZJtsrZiWsMKd8mQ5,NkPAJ3a2nnkTSwNh,yHEkm6R3rmGi7zZ4,Zc8d2hypfafHe2G8,czZSPZQFraP2WArP,Bt6tTBjF4TRh5HhH,nkmWAXskwFHsBCYr,tAyPQ4nBWAXaPtca,Y3h2MCeAE7CFcr2a,aAZfxjkn2CmmhtNJ,bpwSHP6EScHp4bzF
    #土地抵押转房屋抵押流程（原房屋宗地存在抵押,需要注销宗地抵押,生成房屋抵押）
    tddyzfwdy: hbmGmHfkCTxfE7tb
    #抵押查封不换证(产权存在查封抵押,查封抵押不换证,新生成新产权和原查封抵的关联关系)
    withdycfbhz: jsEKwceZQswjPAyx,bbZcnNZM4NNHG42C




  #是否主房, 主房配置，默认为 商业,公寓,住宅 （多个使用英文逗号隔开）
  sfzf:
    zfstr: 商业,公寓,住宅

#部分注销流程读取义务人
sjddy:
   getnowYwr:
#   并案流程两份收件单是一样的，只需要打印一份即可，配置并案流程的定义id，英文逗号隔开
   balcDyid: FFC54pnCBrD7FN26,stAbtHBw7yWNJHQE
   # 只需要打印一份申请书流程定义id(南通配置商品房首次和产权注销的流程)，英文逗号隔开
   oneSqsDyid: hfQ236Q2XSQZtRjS,WR3msbJr8P335c8H
#   需要读取所有的权利人展示在收件单上(配置组合贷款流程)
   getallQlr: pFP7hwxTW2yAfWsQ

#   办件进度二维码地址
   bjjd:
     url: http://gtmapwx.com/wei-plat-jsst/html/jdcx/jdcx.html

   # 收件单打印，是否展示多个收费单二维码，默认：true
   sfdgewm: false
   # 当打印多个二维码为 fasle 时，使用该配置指定打印类型打印多个二维码,多个使用“,”分隔
   dydgewmlx: zhsjd,sjd

#预抵押登记小类
ydydjxl: 7000408,7000410,7000409,7000402

#受理编号生成方式南通版本，合肥配置为空即可
slbhscfs:
   version:

#受理编号配置
slbh:
#自增时间范围（YEAR，MONTH，DAY）
   zzsjfw: DAY
#自增序列号位数
   zzxlh: 5
#部分解押解封 权利类型 对应 规则id
bfjyjf:
  qllxMap:
    95: f16a7ddea1df2c9fb3516a7c8f470106
    98: f16a7d64178f2c9fb3516a7c8f47004c

#判断购物车是否过滤重复的不动产单元号，true去重，false不去重
selectbdcdy:
  repeat: false

# 换证流程计算工本费与其他流程不同，只按照最后出证数量减一即可（以下数据为测试）
hzlc:
  gzldyid: bbZcnNZM4NNHG42C,yHEkm6R3rmGi7zZ4

  # 遗失补证流程计算工本费与其他流程不同，第一本开始收费（以下数据为测试）
ysbz:
  gzldyid: BPCeDrQ7Pb8e2MFQ,kCyhmJRj45XrsKEW

  #房屋抵押权首次登记登记小类（多个用英文逗号隔开）合肥特殊流程收费
fwdyqsc:
  djxl: 9990401,9990405

  #存量房买卖转移登记登记小类（多个用英文逗号隔开）合肥特殊流程收费
clfmmzy:
  djxl: 2000402

#房屋套次统计
fwtccx:
  #规划用途过滤（多个用英文逗号隔开）
  ghyt: 10,11
  #权籍管理代码过滤（前面为当前业务权籍管理代码,后面为需要查询的房产区域权籍管理代码,多个用英文逗号隔开）
  qjgldm:
    340100: 340100,340124
    340124: 340124
  # 舒城房屋套次计算的时候排除农房的数据（农房权利类型为6）
  pcqllx: 6


#收费信息页面 住宅类房屋用途代码(多个用英文逗号隔开)
sfxx:
  zzfwytdm: 85,851,852,853,854,855,10,11,86,100101,100102,100103,100104,100105,100106,100107,100108,100109,100110,100111,100112,100112,100113,100114,100115,100116,100117,10
  fzzfwytdm: 23,24,20,21,22
  #  登记费计算方法 ： 1- 合肥， 2-南通， 3，常州， 4-盐城
  djfjsff: 2
  tsxx: 请确认收费是否正确
  tsdjyysf: '{ 分割析产: "2000402,9990404",测试: "21312,234223" }'
  tssfxmdm: 66
  tssfxmbz: 登记费(析产)/10元
  tssfxmdj: 10
  # 汇总收费统计时 收费标准名称和代码对照关系
  # 收费项目代码在BDC_SL_SFXM_SFBZ表定义
  hzsfxmbz: '{"不动产登记费":"1,2", "土地使用权交易服务费": "6,11"}'
  # 不生成土地收费信息的流程
  bsctdsfxx:
    gzldyids:
  # 缴费办理beanidj集合
  jfblbeanidmap:
    340104: jfbl
  # 缴费确认
  jfqrbeanidmap:
    340104: jfqr
  # 非税开票
  fskpbeanidmap:
    340104: dzpj
  # 作废缴费通知书
  zfjktzsbeanidmap:
    340104: pjzf
  # 初始化收费项目，是否根据登记小类，默认true，淮安false
  sfgjdjxl: false
  #  初始化收费信息，默认jftj 取值 1.商业银行 2. 合一支付
  hyzfjftj:
  # 初始化收费信息，默认缴费类型 1.登记费2.税费统缴
  hyzfjflx:
#  需要计算户室数量的流程定义id
#  counthsslDyids: hfQ236Q2XSQZtRjS

#收费单打印时一卡清二维码内容
sfddy:
  ewmurl:

#默认配置
default:
  # 共有方式默认共同共有登记小类
  gtgyDjxl: 1000603,1000602\
  # 共有方式单个验证：是否开启单个权利人的共有情况只能为单独所有。默认为：true（开启） false（不开启）
  gyfsdgyz: true

#推送省直房改办 登记原因
tsszfgb:
  # 登记原因
  djyy: 已购公有住房买卖（省直）

#部分用户不需要验证是否评价
nochecksfpj:
  username: gln

#外联土地证证书限制状态可注销的流程配置。多个使用英文逗号（,）隔开
wltdzlwxz:
  gzldyid: hfQ236Q2XSQZtRjS

#交易信息用途一对多映射bdc_zd_fwyt的字典
jyxx:
  fwytMap:
    1111: 88,84,85
    2222: 88,84,85
    3333: 1,200204,201503

##邮寄信息
yjxx:
  ## 收件人邮编
  sjryb: 000000
  ## 寄件人信息  区县代码: '{"jjrmc":"寄件人名称","jjrszp":"寄件人所在省","jjrszc":"所在市","jjrszx":"所在区","jjrxxdz":"详细地址","jjryb":"邮编","jjrlxdh":"联系电话"}'
  jjrxxMap:
    ##合肥市
    340100: '{"jjrmc":"张三","jjrszp":"江苏","jjrszc":"南京","jjrszx":"鼓楼","jjrxxdz":"汉中门大街阿斯兰","jjryb":"000000","jjrlxdh":"13900000000"}'
    ##市辖区
    340101: '{"jjrmc": "李四","jjrszp":"浙江","jjrszc":"杭州","jjrszx":"花园","jjrxxdz":"阿里巴巴运营部", "jjryb":"000000","jjrlxdh":"13900000000"}'
    ##瑶海区
    340104: '{"jjrmc": "王五","jjrszp":"深圳","jjrszc":"白云","jjrszx":"","jjrxxdz":"腾讯王者荣耀开发部", "jjryb":"000000","jjrlxdh":"13900000000"}'

#数据版本,不配置默认标准版
data.version: nantong

#一卡清订单有效时间,单位秒,不配置默认600s
ykqddxx.yxsj: 120


#外网申请创建项目忽略验证是否验证
wwsq.zfyzhl: false
#自动转发未认领节点，自动认领节点用户名
wwsq.zfrl:
#一窗商品房转移流程的gzldyid
spf.gzldyid: AXSwxcCC6Y3t3Aer

# 税务接口版本 ：德宽：dk，英塔：yt 默认采用：德宽（dk）版本
swjk.version: dk

# 转移变更并案流程gzldyid
zyhbba.gzldyid: BPphsf77nwdcwB4c

#查档流程
cdlc:
  # 首套房查询
  stfcx.gzldyid: tEHHRtMtj3D7HjsW
  #三调查询
  sdcx.gzldyid:

# 南通推送税务根据房屋用途确定当前建筑面积是阁楼面积还是车库面积等
# 字典类型顺序：车库;储藏室;阁楼  ,剩下的未配置的为权属转移面积类型
swjk.tsswFdcqGhyt: 10,20;30,40;51

# 南通推送税务附件传递URL地址，由税务自行异步下载，大云附件地址税务不通，需要替换为映射地址端口
# 这里配置税务访问大云附件地址映射 IP 和 端口
swjk.fj.ip_port: 192.168.2.99:8030

# 安徽一窗办理，查询税务（德宽），申报提醒函下载地址配置
swjk.sbtxh.ip_port: 59.203.19.50:9790

# 打印模板地址配置
print.path: E:\GTIS\print\

#打印类型自定义申请书
print.sqs.dylx: scsqs,zysqs,zhsqs
#打印类型自定义收件单
print.sjd.dylx: scsjd,zysjd,zhsjd,sjd
#需要获取校验查询二维码的打印类型
print.jycxewm.dylx: bdcdjbcxfcztdz340104,stfzm340104
#组合流程打印一份的打印类型
print.zhlc.one.dyxl: zhsjd,zhsqs

# 外网创建时 自动计算收费项目内容（合肥）
wwsq.zdjssfxm.lcsplymap:
  jsEKwceZQswjPAyx: 5
  AXSwxcCC6Y3t3Aer: 2,3,4,5

# 定时缴库配置
#配置需要验证收费信息的时间范围：0/1~0/30 表示周期为每月1-30号；  -1/15~0/15 表示为上月15号到本月15号
#注：cron 配置每月10号执行， 当前时间为5月，则0/1~0/30 表示周期为4月的1-30号； -1/15~0/15 表示为3月15号到4月15号
quartz:
  tsjk.enable: false
  tsjk.cron: 0 0 22 * * ?
  yzyjyhzt.enable: false
  yzyjyhzt.cron: 0 0 22 15 * ?
  yzyjyhzt.time: -1/15~0/15
  # 银行黑名单解除定时任务，enbale：是否开启定时任务（false：不开启，true：开启） cron: 定时任务执行时间（每晚11点）
  yhhmdjc.enable: false
  yhhmdjc.cron: 0 0 23 * * ?

zhdk.gzldyid: pFP7hwxTW2yAfWsQ

#收件材料上传后是否更新页数
sjcl.gxys: true
#配置收件材料根据登记原因切换时重新创建是否删除之前所有的还是只删除未上传文件的
sjcl.recreate.deleteAll: false
#组合流程收件材料分开收件
zhlc.splitsjcl: true

# 水印图片地址
watermark.image.path: /usr/local/bdc3/print/watermark.png

# 非税缴款书URL
fs.jfsbmurl: http://pay.jscz.gov.cn/fntop/qrcode?billId=

# 获取的登记原因收件材料为空时，是否根据登记小类生成收件材料
sjcl.djyynocl.sfcjsjcl: false
# 是否获取是否必传的收件材料
sjcl:
  yzsfbc: true
# 流程创建是否验证角色下方部门  默认为null：不验证， 1：验证
cjlc.verifyRoleDepartment:

#非登记业务流程
fdjywlc:
  gzldyid:
    #资金监管流程
    zjjg: RWwCySCZ8RX37wQi
    #资金监管撤销流程
    zjjgcx: Q5sABnEc5xFwHsh5
    qjdc: HmzWm67NCXQRbSa6
    #权利人查询，首套房查询，权利人查询(盐城)
    cdxx: Tm3eQrfDe2YM6F6F,tEHHRtMtj3D7HjsW,mMGbh58mNCMDdfW4
    xzlc: iyBbGP2f2HDNABjD,PW6J5fD8NfZHXN4e
    ywlz: iwiSMbTcycBSr2Di
    #    改变权属状态流程
    xzqszt: dQYmEadb4QJrSjy7
    fgyhsf: tjEkWSYix4QPBJHJ
    #不予登记或者不予受理信息
    bysl: apBdcQhpJjjzhJrT
    bydj: apBdcQhpJjjzhJrT
# 配置需要从登记库生成打印数据源的  打印类型，不需要在代码里面再新增打印类型
dysjy.djk.dylx: zxpz,bdcygdjzmd,xwbl,lqsqs,lqsqspl,clfmmht,zysqs,dysqs
dysjy.slk.dylx: bysld,bdczlcxsqs,bdcdjbcxbdcqz,fgzjcsjd,fgzjcsjd1,stfzm,jfspl,ywlzd,stfzm_0,bdcdjbcxfcztdz,jcgg,
  bdcdjbcxfcztdz340104,stfzm340104,djbcxfwqd,tdfssrybjks,zxsjd,zysjd,dysjd

# 南通推送税务,推送曾用名
swjk.tscym: true

#默认收费信息
mrsfxx:
  #默认收费信息Map
  mrsfxxMap:
    #行政区代码
    340111:
      # 收费单位代码
      sfdwdm: 111
      # 收费人姓名
      sfrxm: 收费人姓名
      # 收费单位名称
      sfdwmc: 收费单位名称
      # 收费人账号
      sfrzh: 222
      # 收费人开户银行
      sfrkhyh: 收费人开户银行
      # 收费人开户银行网点代码
      sfrkhyhwddm: 333
#配置司法裁决工作流定义id
sfcj.gzldyid: iTEz3K8KS226khn4
sfcjzy.gzldyid: EdNed5GdbDspXYCj

# 配置去除 "等" 字样的工作流定义ID
qcjd.gzldyids: jsEKwceZQswjPAyx,TDpCMQxerjDPnp6Y

#受理库数据根据项目数量打印多份
plslkdy.dylx: bdcdjbcxbdcqz,bdcdjbcxfcztdz
#一证多房不需要批量打印
noplslkdylx.yzdf.dylx: bdcdjbcxbdcqz,bdcdjbcxfcztdz
#收费信息是否月结默认否的流程
sfxx.sfyjmrf: pQcQQYfWJX5riHwd

zdyzlcsh.qllxAndYwrsjly.fJpChN4ZBskPnZMZ: '{"4": "2", "95":"3"}'

sfxx.bsf.fjhcontains: 阁
#土地使用权收费项目代码
sfxx.sfxm.tdsyqsfxmdm: 320400

# 收件材料继承上一手数据的流程
sjcl.extendYxm.gzldyid: r5wJBF4dZbPFXbzf
#继承上一手收件材料不需要的文件夹
sjcl.extendYxm.exceptclmc: 审批表

qxdmfilter.zzjgQxdm: '{"340104": "340104,340104,340104"}'

# 盐城的收费状态不包含‘不收费’，金额为0时，不更新收费状态
#sfxx.sfzt.bsf: false

dzqm:
  gzldyid: jsEKwceZQswjPAyx

cjyz:
  lwsh: true
pjq:
  qxdmPjqbbMap:
    340111: MK_L
    320412: MK_N
    320481: QDWS
  qxdmUrlMap:
    340111: http://127.0.0.1:27100/evaluate/startEvaluate?xzqdm=320111&wdbs=320111&ywbh=@{slbh}&jdmc=@{jdmc}&blry=@{slr}&sqrxm=@{qlrmc}&sqrlxfs=@{qlrlxfs}
    320412:
    320481: http://127.0.0.1:27100/Terminal?t=Evaluate&xzqdm=320481&wdbs=320481&ywbh=@{slbh}&jdmc=@{jdmc}&blry=@{slr}&sqrxm=@{qlrmc}&sqrlxfs=@{qlrlxfs}
#  qxdmRzdbbbMap:
#    340111: MK_L
#    320481: QDWS
  qxdmrzbdUrlMap:
    340111: http://127.0.0.1:27100/man_identity/data/showList?serviceId=@{slbh}
    320481: http://127.0.0.1:27100/Terminal?t=FaceValidateWithIdCard&ServiceId=@{slbh}

# 南通打印电子发票接口配置
fs.config.dzfp.beanName.340104: fs_srpt_dzfpxz
# 南通推送收费信息接口配置
fs.config.ts.beanName.340104: fs_srpt_tsdjfxx
# 南通作废收费信息接口配置
fs.config.zf.beanName.340104: fs_srpt_zfdjfxx
# 南通换开电子发票接口
fs.config.hkdzfp.beanName.340104: fs_srpt_hkdzfp

##解封产权合并
lcbs.jfcqhb: JKnA2wHjnJ5WYjCd
##解押产权合并
lcbs.dyzxcqhb: dMK7ymc5QCzf8eNH
#上报校验排除非登记业务流程
sbjy.fdjywlc.gzldyid:
##单元号更正登记
lcbs.dyhgz: mTjF5njF5AmFk5Zz

config:
  qjgldmfilter: true
qjgldmfilter:
  zzjgQjgldm: '{"340104":"340100,340124","340111":"340100"}'
xztz:
  qjgldmfilter:
    version: new

#批量流程根据项目数量打印多份
pllc:
  dydf:
    dylx: dyzxsqs
plzh:
  dydf:
    dylx: zxsqs

bysl.gzsbhqz: '{"340100":"武","320400":"金"}'
ycsl.xtid: '{"340100":"1231231","340110":"222333"}'

swxx:
  qxdmdz: '{"340102":"340103","340110":"222333"}'

wlzs:
  wlzsdytofwdy: hfQ236Q2XSQZtRjS

wwsq:
  sfcshsfxm: true
  scslbh:
    sply: 16

sjgsdq:
  sjly: ssxz

