info:
  name: ${spring.application.name}
  component: inquiry application

app:
  center: http://192.168.2.70:8000/eureka/
  oauth: http://192.168.2.70:8030/account
  security:
    moduleAuthPath: http://account/account
    # 开放权限：静态资源、打印接口、住房查询接口
    ignores: /image/**,/css/**,/js/**,/webjars/**,/realestate-inquiry/rest/v1.0/print/**,/realestate-inquiry/rest/v1.0/zfxx/**,/realestate-inquiry/rest/v1.0/test/**
    authorities:
      permitAll: /index2
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**,/index
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated: true
    resources:
      authenticated: /realestate-inquiry/**
  services:
#    accept-app: accept-app3
#    inquiry-app: inquiry-app3
#    init-app: init-app-yan
#    register-app: register-app3

spring:
  rabbitmq:
    host: 192.168.2.72
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 127.0.0.1
  elasticsearch:
    jest:
      uris: http://192.168.2.71:9200
      connection-timeout: 80000
      read-timeout: 80000
      username: elastic
      password: gtmap123456
  datasource:
    url: jdbc:oracle:thin:@192.168.2.111:1521/orcl
    username: bdcdj_pz
    password: WAZyOcKhvgDjnBbP0C70W3jkWKgpudwUsLH0ojka0XYZVrKr6bRgWyaPtoFAdJr1m025jullQJj0Q7h3JdJLVQ==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIkhcbmyW8IgYViVU/4dKr+FUy0P9mSYhYLIgtlf2arzKI0ohb6/H0aUf4zWsW+GSRwECGmQbSKzOplzfeSELqUCAwEAAQ==

  cloud-data-source:
    url: jdbc:oracle:thin:@192.168.2.111:1521/orcl
    username: workflow
    password: WAZyOcKhvgDjnBbP0C70W3jkWKgpudwUsLH0ojka0XYZVrKr6bRgWyaPtoFAdJr1m025jullQJj0Q7h3JdJLVQ==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIkhcbmyW8IgYViVU/4dKr+FUy0P9mSYhYLIgtlf2arzKI0ohb6/H0aUf4zWsW+GSRwECGmQbSKzOplzfeSELqUCAwEAAQ==
  messages:
    basename: conf/message/messages, conf/message/errors
  profiles:
    include: config
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB

management:
  security:
    enabled: true
  context-path:

endpoints:
  enabled: true
  shutdown:
    enabled: true

server:
  port: ${port:8599}
  max-http-header-size: 10485760

logging:
  level:
    org.springframework: WARN
    cn.gtmap.gtc.plugins: DEBUG
    cn.gtmap.realestate.inquiry.core.mapper: DEBUG

# 查询子系统 liquibase 配置
liquibase:
  change-log: classpath:changelog/master.xml
  enabled: true
  drop-first: false

# 打印fr3文件保存服务器路径
print:
  path: C:\\GTIS\\print\\
