info:
  name: InterchangeApp
  component: Interchange Application


server:
  port: ${port:9996}

logging:
  level:
    org.springframework: WARN

spring:
  datasource:
    gx:
      url: jdbc:oracle:thin:@192.168.2.86:1521/orcl
      username: bdcdj_hefei
      password: gtis
    yzw:
      url: jdbc:oracle:thin:@192.168.2.86:1521/orcl
      username: bdcsl_hefei
      password: gtis


quartz:
  tsgxsj:
    enable: true
    # 每一份种执行一次
    #cron: 0 */1 * * * ?
    cron: 0 */1 * * * ?