--liquibase formatted sql
--preconditions dbms:oracle
--changeset bdc_sl_yjxx:1 failOnError:false runOnChange:true runAlways:false

CREATE TABLE BDC_SL_YJXX
  (
    YJXXID  VARCHAR2(32) NOT NULL ENABLE,
    GZLSLID VARCHAR2(32),
    SLBH    VARCHAR2(50),
    SJRMC   VARCHAR2(200),
    SJRYB   VARCHAR2(6),
    SJRLXDH VARCHAR2(15),
    SJRXXDZ VARCHAR2(2000),
    SJRSZP  VARCHAR2(100),
    SJRSZC  VARCHAR2(100),
    SJRSZX  VARCHAR2(100),
    JJRMC   VARCHAR2(200),
    JJRYB   VARCHAR2(6),
    JJRLXDH VARCHAR2(15),
    JJRXXDZ VARCHAR2(2000),
    JJRSZP  VARCHAR2(100),
    JJRSZC  VARCHAR2(100),
    JJRSZX  VARCHAR2(100),
    TSZT    NUMBER(1,0) DEFAULT 0,
    TSSJ DATE,
    WLDDH VARCHAR2(100),
    WLYDH VARCHAR2(100),
    constraint BDC_SL_YJXX primary key(YJXXID)
);
COMMENT ON COLUMN BDC_SL_YJXX.YJXXID IS '邮寄信息id';
COMMENT ON COLUMN BDC_SL_YJXX.GZLSLID IS '工作流实例id';
COMMENT ON COLUMN BDC_SL_YJXX.SLBH IS '受理编号(可作为接口订单号，查询订单状态信息)';
COMMENT ON COLUMN BDC_SL_YJXX.SJRMC IS '收件人名称';
COMMENT ON COLUMN BDC_SL_YJXX.SJRYB IS '收件人邮编';
COMMENT ON COLUMN BDC_SL_YJXX.SJRLXDH IS '收件人联系电话';
COMMENT ON COLUMN BDC_SL_YJXX.SJRXXDZ IS '收件人详细地址';
COMMENT ON COLUMN BDC_SL_YJXX.SJRSZP IS '收件人所在省';
COMMENT ON COLUMN BDC_SL_YJXX.SJRSZC IS '收件人所在市';
COMMENT ON COLUMN BDC_SL_YJXX.SJRSZX IS '收件人所在县';
COMMENT ON COLUMN BDC_SL_YJXX.JJRMC IS '寄件人名称';
COMMENT ON COLUMN BDC_SL_YJXX.JJRYB IS '寄件人邮编';
COMMENT ON COLUMN BDC_SL_YJXX.JJRLXDH IS '寄件人联系电话';
COMMENT ON COLUMN BDC_SL_YJXX.JJRXXDZ IS '寄件人详细地址';
COMMENT ON COLUMN BDC_SL_YJXX.JJRSZP IS '寄件人所在省';
COMMENT ON COLUMN BDC_SL_YJXX.JJRSZC IS '寄件人所在市';
COMMENT ON COLUMN BDC_SL_YJXX.JJRSZX IS '寄件人所在县';
COMMENT ON COLUMN BDC_SL_YJXX.TSZT IS '是否已推送至EMS(1:已推送  0：未推送)';
COMMENT ON COLUMN BDC_SL_YJXX.TSSJ IS '推送时间';
COMMENT ON COLUMN BDC_SL_YJXX.WLDDH IS '物流订单号';
COMMENT ON COLUMN BDC_SL_YJXX.WLYDH IS '物流运单号';
CREATE INDEX "BDC_SL_YJXX_GZLSLID_INDEX" ON BDC_SL_YJXX (GZLSLID);

--changeset bdc_sl_yjxx:2 failOnError:false runOnChange:true runAlways:false
ALTER TABLE BDC_SL_YJXX  ADD(DZYX VARCHAR2(100));
COMMENT ON COLUMN BDC_SL_YJXX.DZYX IS '电子邮箱';

--changeset bdc_sl_yjxx:3 failOnError:false runOnChange:true runAlways:false
ALTER TABLE BDC_SL_YJXX  ADD(DJXL VARCHAR2(10));
COMMENT ON COLUMN BDC_SL_YJXX.DJXL IS '登记小类';
ALTER TABLE BDC_SL_YJXX  ADD(SJRZJH VARCHAR2(100));
COMMENT ON COLUMN BDC_SL_YJXX.SJRZJH IS '收件人证件号';