--liquibase formatted sql
--preconditions dbms:oracle
--changeset BDC_SL_JYXX_CEZS:1 failOnError:false runOnChange:true runAlways:false
CREATE TABLE BDC_SL_JYXX_CEZS
  (
    CEZSID VARCHAR2(32 BYTE) NOT NULL ENABLE,
    XMID  VARCHAR2(32 BYTE) NOT NULL ENABLE,
    YJYLX  NUMBER(1,0),
    YYHS   NUMBER(22,6),
    YDJF   NUMBER(22,6),
    YQTFY  NUMBER(22,6),
    ZFZXFY NUMBER(22,6),
    ZFDKLX NUMBER(22,6),
    GZFY   NUMBER(22,6),
    QTFY   NUMBER(22,6)
  );
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.CEZSID IS '差额征收ID';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.XMID IS '项目ID';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.YJYLX IS '原交易类型';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.YYHS IS '原印花税';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.YDJF IS '原登记费';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.YQTFY IS '原其他税费';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.ZFZXFY IS '住房装修费用';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.ZFDKLX IS '住房贷款利息';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.GZFY IS '公证费用';
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.QTFY IS '其他费用';
CREATE UNIQUE INDEX BDC_SL_JYXX_CEZS_CEZSID ON BDC_SL_JYXX_CEZS ( CEZSID );
CREATE INDEX BDC_SL_JYXX_CEZS_XMID ON BDC_SL_JYXX_CEZS ( XMID );


--changeset BDC_SL_JYXX_CEZS:2 failOnError:false runOnChange:true runAlways:false
ALTER TABLE BDC_SL_JYXX_CEZS ADD YWXJJ NUMBER(22,6);
COMMENT ON COLUMN BDC_SL_JYXX_CEZS.YWXJJ IS '原维修基金';
