--liquibase formatted sql
--preconditions dbms:oracle
--changeset bdc_sl_tfxx:1 failOnError:false runOnChange:true runAlways:false

CREATE TABLE BDC_SL_TFXX
  (
    TFXXID    VARCHAR2(32) NOT NULL ENABLE,
    SFXXID    VARCHAR2(32),
    SLBH      VARCHAR2(32),
    JFSBM     VARCHAR2(32),
    JKRXM     VARCHAR2(100),
    SFSJ      DATE,
    DJF       NUMBER(20,4),
    TDSYQJYFWF     NUMBER(20,4),
    SJSFZJE        NUMBER(20,4),
    SJTFZJE        NUMBER(20,4),
    PJLX      VARCHAR2(100),
    SQTFSJ    DATE,
    SQTFYY    VARCHAR2(500),
    BMMC      VARCHAR2(100),
    constraint BDC_SL_TFXX primary key (TFXXID)
);
COMMENT ON COLUMN BDC_SL_TFXX.TFXXID IS '退费信息ID';
COMMENT ON COLUMN BDC_SL_TFXX.SFXXID IS '收费信息ID';
COMMENT ON COLUMN BDC_SL_TFXX.SLBH IS '受理编号';
COMMENT ON COLUMN BDC_SL_TFXX.JFSBM IS '缴费书编码';
COMMENT ON COLUMN BDC_SL_TFXX.JKRXM IS '缴款人姓名';
COMMENT ON COLUMN BDC_SL_TFXX.SFSJ IS '收费时间';
COMMENT ON COLUMN BDC_SL_TFXX.DJF IS '不动产登记费';
COMMENT ON COLUMN BDC_SL_TFXX.TDSYQJYFWF IS '土地使用权交易服务费';
COMMENT ON COLUMN BDC_SL_TFXX.SJSFZJE IS '实际收费总金额';
COMMENT ON COLUMN BDC_SL_TFXX.SJTFZJE IS '实际退费总金额';
COMMENT ON COLUMN BDC_SL_TFXX.PJLX IS '票据类型';
COMMENT ON COLUMN BDC_SL_TFXX.SQTFSJ IS '申请退费时间';
COMMENT ON COLUMN BDC_SL_TFXX.SQTFYY IS '申请退费原因';
COMMENT ON COLUMN BDC_SL_TFXX.BMMC IS '部门名称';
CREATE INDEX "BDC_SL_TFXX_JFSBM_INDEX" ON BDC_SL_TFXX (JFSBM);
CREATE INDEX "BDC_SL_TFXX_SLBH_INDEX" ON BDC_SL_TFXX (SLBH);
