--liquibase formatted sql
--preconditions dbms:oracle
--changeset bdc_sl_fpxx_xgjl:1 failOnError:false runOnChange:true runAlways:false

CREATE TABLE BDC_SL_FPXX_XGJL
  (
    XGJLID  VARCHAR2(32) NOT NULL ENABLE,
    FPH     VARCHAR2(32),
    SLBH    VARCHAR2(32),
    ZL      VARCHAR2(200),
    JKRXM   VARCHAR2(50),
    XGSJ    DATE,
    XGQZD   VARCHAR2(2000),
    XGHZD   VARCHAR2(2000),
    XGR   VARCHAR2(50),
    XMID  VARCHAR2(32),
    constraint BDC_SL_FPXX_XGJL primary key (XGJLID)
);
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.XGJLID IS '修改记录ID';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.FPH IS '发票号';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.SLBH IS '受理编号';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.ZL IS '坐落';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.JKRXM IS '缴费人姓名';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.XGSJ IS '修改时间';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.XGQZD IS '修改前字段';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.XGHZD IS '修改后字段';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.XGR IS '修改人';
COMMENT ON COLUMN BDC_SL_FPXX_XGJL.XMID IS '项目ID';
CREATE INDEX "BDC_SL_FPXX_XGJL_FPH_INDEX" ON BDC_SL_FPXX_XGJL (FPH);
CREATE INDEX "BDC_SL_FPXX_XGJL_SLBH_INDEX" ON BDC_SL_FPXX_XGJL (SLBH);