info:
  name: ${spring.application.name}
  component: building application

app:
  center: http://192.168.10.87:8000/eureka/
  oauth: http://192.168.10.87:8002/account

  security:
    moduleAuthPath: http://account/account
    ignores: /**,/image/**,/css/**,/js/**,/webjars/**,/building/test/**,/building/rest/v1.1/bdcdy/**,/building/rest/v1.0/djxx/**,/building/rest/v1.0/ychs/**,/building/rest/v1.0/gzw/**,/building/rest/v1.0/hs/fwdcbindex/**
    authorities:
      permitAll:
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**,/index
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated : true
    resources:
      authenticated: /building/**
#      hasScope('get_building_info'): /resource/**,/catalog/**,/building/**

spring:
  rabbitmq:
    host: 192.168.10.87
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 192.168.10.87
  datasource:
    url: jdbc:oracle:thin:@192.168.10.165:1521/orcl
    username: bdcsjgl_3
    password: e/lWYHJj7d9rXmgsItIxLw2oWP4XasfqoDXA0AKNYHgeSJQK8IKgU8/+ia1ax4mr9ki4QZbrQrCW9WMkHDOPAA==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK8ev+xi3qANIZpQGhndeKtc2EOlsPd48VIhphnl3OoOKqynJuQo7qZrJekk8iqXHgvze3bnFrFyTtf3vxGIamsCAwEAAQ==
#    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK8ev+xi3qANIZpQGhndeKtc2EOlsPd48VIhphnl3OoOKqynJuQo7qZrJekk8iqXHgvze3bnFrFyTtf3vxGIamsCAwEAAQ==
  messages:
    basename: conf/message/messages, conf/message/errors


server:
  port: ${port:8666}

# 房屋图层表名
fwkTableName: fw_k_2301
# 变更号的序列名
maxBgbhSeq: maxbh_bgbh2019
# 户室合并操作是否弹窗选择需要继承的子户室
hsfrzhsz: 1



# 同步状态的定时任务
synczt.task: true
# 同步状态定时任务 是否使用ES作为扫描依据
# false时为扫描业务库当天办结业务的BDCDYH
synczt.task.withes: true
# 同步状态定时任务的CRON表达式
synczt.cron: 0 0 22 * * ?

# 读取权籍宗地图功能 FTP配置
zdtFtp:
  ip: 192.168.10.84
  port: 21
  username: gt
  password: gtis
  path: /宗地图
  pathF: /宗地图2

# 宗地图服务实现：南通：readZdtFromDbBase64ServiceImpl，合肥：readZdtHefeiFtpServiceImpl
# 不配默认合肥配置
zdtService: readZdtHefeiFtpServiceImpl
# 地区版本
sysversion: hefei
# 南通特殊需求处理
# 从TUXKNR表中读取宗地图时需要提供下载，此处配置为下载URL
tuxknr.downurl: http://#IP#:#PORT#/fileCenter/file/get.do?token=whosyourdaddy&fid=
#地籍调查表需展示的TAB页依次为：宗地调查表、权属调查表、界址标志表、房屋信息（F类型BDCDYH才显示）、
#宗地图、分层分户图（F类型BDCDYH才显示）、不动产单元定位
#不配置默认有zddcb,qsdc,jzbsb,fwxx,zdt
djdcb.view.tabs: zddcb,qsdc,jzbsb,fwxx,zdt,fcfht,omp

# 蚌埠特殊处理
bengbu:
  # 权籍库中bdcdyh既存在fw_hs表又存在fw_lzj表时候，如果是独幢类型，优先当作独幢处理
  hs_ljz_dz: true

