info:
  name: ${spring.application.name}
  component: natural-resource application

app:
  center: http://192.168.2.99:8000/eureka/
  oauth: http://192.168.2.99:8002/account
  security:
    moduleAuthPath: http://account/account
    ignores: /image/**,/css/**,/js/**,/webjars/**,/realestate-natural-resource/rest/v1.0/**
    authorities:
      permitAll: /index2
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**,/index
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated: true
    resources:
         authenticated: /resource/**,/catalog/**,/realestate-natural-resource/rest/v1.0/**
  services:
spring:
  rabbitmq:
    host: 192.168.0.60
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 192.168.0.60
  datasource:
    url: jdbc:oracle:thin:@192.168.2.86:1521/orcl
      #    url: jdbc:oracle:thin:@10.118.30.31:1521/orcl
    #    username: bdcsl
    username: zrzydj
    password: e/lWYHJj7d9rXmgsItIxLw2oWP4XasfqoDXA0AKNYHgeSJQK8IKgU8/+ia1ax4mr9ki4QZbrQrCW9WMkHDOPAA==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK8ev+xi3qANIZpQGhndeKtc2EOlsPd48VIhphnl3OoOKqynJuQo7qZrJekk8iqXHgvze3bnFrFyTtf3vxGIamsCAwEAAQ==
  messages:
        basename: conf/message/messages, conf/message/errors
  profiles:
        include: config  #引入配置文件 application-config.yml

liquibase:
  #变更日志配置路径(默认值 classpath:/db/changelog/db.changelog-master.yaml)
  change-log: classpath:changelog/master.xml
   #开启liquibase支持(默认值 true)
  enabled: true
  #先删除数据库schema(默认值 false)
  drop-first: false

server:
  port: ${port:8703}

logging:
  level:
    org.springframework: WARN
    cn.gtmap.gtc.plugins: DEBUG
url:


