dzgx:
  #权利和表的对照关系(不变)
  qllxMap:
    1: BDC_TDSYQ
    2: BDC_TDSYQ
    3: BDC_JSYDSYQ
    4: BDC_FDCQ
    5: BDC_JSYDSYQ
    6: BDC_FDCQ
    7: BDC_JSYDSYQ
    8: BDC_FDCQ
    9: BDC_TDCBNYDSYQ
    11: BDC_LQ
    12: BDC_LQ
    13: BDC_TDCBNYDSYQ
    14: BDC_TDCBNYDSYQ
    15: BDC_HYSYQ
    16: BDC_GJZWSYQ
    17: BDC_HYSYQ
    18: BDC_GJZWSYQ
    19: BDC_DYIQ
    20: BDC_QTXGQL
    21: BDC_QTXGQL
    22: BDC_QTXGQL
    23: BDC_TDCBNYDSYQ
    24: BDC_GJZWSYQ
    25: BDC_GJZWSYQ
    26: BDC_GJZWSYQ
    30: BDC_TDCBNYDSYQ
    31: BDC_LQ
    33: BDC_LQ
    34: BDC_LQ
    35: BDC_LQ
    36: BDC_LQ
    50: BDC_NYDJYQ
    92: BDC_JZQ
    93: BDC_FWZL
    94: BDC_FDCQ3
    37: BDC_DYAQ
    96: BDC_YG
    97: BDC_YY
    98: BDC_CF
    99: BDC_QTXGQL
  #不动产类型和抵押不动产类型的对照关系(不变)
  dybdclxMap:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 2
    9: 7
    10: 2
    11: 3
    12: 7
    13: 7