package cn.gtmap.realestate.etl.core.domian.ycsl;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Thu Aug 02 16:19:23 CST 2018.</p>
 *
 * @author huangzijian
 */

@Entity
@Table(name = "YCSL_BDCDYXX")
public class YcslBdcdyxxDo implements Serializable {


    private static final long serialVersionUID = 7268101413050705945L;


    /**
     * 主键
     */
    @Column(name = "BDCDYXXID")
    @Id
    private String bdcdyxxid;

    /**
     * 不动产单元号
     */
    @Column(name = "BDCDYH")
    private String bdcdyh;

    /**
     * 房产编号
     */
    @Column(name = "FCBH")
    private String fcbh;

    /**
     * 不动产类型
     */
    @Column(name = "BDCLX")
    private String bdclx;

    /**
     * 定着物用途
     */
    @Column(name = "DZWYT")
    private String dzwyt;

    /**
     * 宗地宗海用途
     */
    @Column(name = "ZDZHYT")
    private String zdzhyt;

    /**
     * 宗地宗海权利性质
     */
    @Column(name = "ZDZHQLXZ")
    private String zdzhqlxz;

    /**
     * 房源信息来源(1：增量房；2：存量房)
     */
    @Column(name = "FYXXLY")
    private String fyxxly;

    /**
     * 坐落
     */
    @Column(name = "ZL")
    private String zl;

    /**
     * 定作物面积
     */
    @Column(name = "DZWMJ")
    private String dzwmj;

    /**
     * 项目id
     */
    @Column(name = "PROID")
    private String proid;

    /**
     * 流程id
     */
    @Column(name = "WIID")
    private String wiid;

    /**
     * 数据归属地区
     */
    @Column(name = "SJGSDQ")
    private String sjgsdq;

    /**
     * 上次交易金额
     */
    @Column(name = "SCJYJE")
    private Double scjyje;

    /**
     * 上次交易合同登记时间
     */
    @Column(name = "SCJYDJSJ")
    private Date scjydjsj;

    /**
     * 行政区划数字代码
     */
    @Column(name = "XZQHSZDM")
    private String xzqhszdm;

    /**
     * 街道乡镇代码
     */
    @Column(name = "JDXZDM")
    private String jdxzdm;

    /**
     * 产权证号
     */
    @Column(name = "CQZH")
    private String cqzh;

    /**
     * 备注
     */
    @Column(name = "BZ")
    private String bz;

    /**
     * 宗地宗海面积
     */
    @Column(name = "ZDZHMJ")
    private Double zdzhmj;

    /**
     * 初始登记证号
     */
    @Column(name = "CSDJZH")
    private String csdjzh;

    public String getBdcdyxxid() {
        return this.bdcdyxxid;
    }

    public void setBdcdyxxid(String bdcdyxxid) {
        this.bdcdyxxid = bdcdyxxid;
    }

    public String getBdcdyh() {
        return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }

    public String getFcbh() {
        return this.fcbh;
    }

    public void setFcbh(String fcbh) {
        this.fcbh = fcbh;
    }

    public String getBdclx() {
        return this.bdclx;
    }

    public void setBdclx(String bdclx) {
        this.bdclx = bdclx;
    }

    public String getDzwyt() {
        return this.dzwyt;
    }

    public void setDzwyt(String dzwyt) {
        this.dzwyt = dzwyt;
    }

    public String getZdzhyt() {
        return this.zdzhyt;
    }

    public void setZdzhyt(String zdzhyt) {
        this.zdzhyt = zdzhyt;
    }

    public String getZdzhqlxz() {
        return this.zdzhqlxz;
    }

    public void setZdzhqlxz(String zdzhqlxz) {
        this.zdzhqlxz = zdzhqlxz;
    }

    public String getFyxxly() {
        return this.fyxxly;
    }

    public void setFyxxly(String fyxxly) {
        this.fyxxly = fyxxly;
    }

    public String getZl() {
        return this.zl;
    }

    public void setZl(String zl) {
        this.zl = zl;
    }

    public String getDzwmj() {
        return this.dzwmj;
    }

    public void setDzwmj(String dzwmj) {
        this.dzwmj = dzwmj;
    }

    public String getProid() {
        return this.proid;
    }

    public void setProid(String proid) {
        this.proid = proid;
    }

    public String getWiid() {
        return this.wiid;
    }

    public void setWiid(String wiid) {
        this.wiid = wiid;
    }

    public String getSjgsdq() {
        return this.sjgsdq;
    }

    public void setSjgsdq(String sjgsdq) {
        this.sjgsdq = sjgsdq;
    }

    public Double getScjyje() {
        return this.scjyje;
    }

    public void setScjyje(Double scjyje) {
        this.scjyje = scjyje;
    }

    public Date getScjydjsj() {
        return this.scjydjsj;
    }

    public void setScjydjsj(Date scjydjsj) {
        this.scjydjsj = scjydjsj;
    }

    public String getXzqhszdm() {
        return this.xzqhszdm;
    }

    public void setXzqhszdm(String xzqhszdm) {
        this.xzqhszdm = xzqhszdm;
    }

    public String getJdxzdm() {
        return this.jdxzdm;
    }

    public void setJdxzdm(String jdxzdm) {
        this.jdxzdm = jdxzdm;
    }

    public String getCqzh() {
        return this.cqzh;
    }

    public void setCqzh(String cqzh) {
        this.cqzh = cqzh;
    }

    public String getBz() {
        return this.bz;
    }

    public void setBz(String bz) {
        this.bz = bz;
    }

    public Double getZdzhmj() {
        return this.zdzhmj;
    }

    public void setZdzhmj(Double zdzhmj) {
        this.zdzhmj = zdzhmj;
    }

    public String getCsdjzh() {
        return csdjzh;
    }

    public void setCsdjzh(String csdjzh) {
        this.csdjzh = csdjzh;
    }
}
