package cn.gtmap.realestate.etl.core.domian.ycsl;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Thu Aug 02 16:19:23 CST 2018.</p>
 *
 * @author huangzijian
 */

@Entity
@Table(name = "YCSL_FWXX")
public class YcslFwxxDo implements Serializable {


    private static final long serialVersionUID = 6990707080979985088L;


    /**
     * 主键
     */
    @Column(name = "FWXXID")
    @Id
    private String fwxxid;

    /**
     * 不动产单元信息id
     */
    @Column(name = "BDCDYXXID")
    private String bdcdyxxid;

    /**
     * 不动产单元号
     */
    @Column(name = "BDCDYH")
    private String bdcdyh;

    /**
     * 项目名称
     */
    @Column(name = "XMMC")
    private String xmmc;

    /**
     * 房屋性质
     */
    @Column(name = "FWXZ")
    private String fwxz;

    /**
     * 房屋结构
     */
    @Column(name = "FWJG")
    private String fwjg;

    /**
     * 所在层
     */
    @Column(name = "SZC")
    private Integer szc;

    /**
     * 总层数
     */
    @Column(name = "ZCS")
    private Integer zcs;

    /**
     * 物理层
     */
    @Column(name = "WLC")
    private Integer wlc;

    /**
     * 房屋类型
     */
    @Column(name = "FWLX")
    private String fwlx;

    /**
     * 所在名义层
     */
    @Column(name = "SZMYC")
    private String szmyc;

    /**
     * 层高
     */
    @Column(name = "CG")
    private Double cg;

    /**
     * 名义总层数
     */
    @Column(name = "MYZCS")
    private String myzcs;

    /**
     * 自然幢号
     */
    @Column(name = "ZRZH")
    private String zrzh;

    /**
     * 房间号
     */
    @Column(name = "FJH")
    private String fjh;

    /**
     * 建筑面积
     */
    @Column(name = "JZMJ")
    private Double jzmj;

    /**
     * 套内面积
     */
    @Column(name = "TNMJ")
    private Double tnmj;

    /**
     * 规划用途
     */
    @Column(name = "GHYT")
    private String ghyt;

    /**
     * 房源编号
     */
    @Column(name = "FYBH")
    private String fybh;

    /**
     * 房屋属地税务机关
     */
    @Column(name = "FWSDSWJG")
    private String fwsdswjg;

    /**
     * 房屋所在地行政区划
     */
    @Column(name = "FWSZDXZQH")
    private String fwszdxzqh;

    /**
     * 房屋所在地所处街乡
     */
    @Column(name = "FWSZDSCJX")
    private String fwszdscjx;

    /**
     * 道路名称
     */
    @Column(name = "DLMC")
    private String dlmc;

    /**
     * 小区名称
     */
    @Column(name = "XQMC")
    private String xqmc;

    /**
     * 朝向
     */
    @Column(name = "CX")
    private String cx;

    /**
     * 单元号
     */
    @Column(name = "DYH")
    private String dyh;

    /**
     * 房屋/土地总价格
     */
    @Column(name = "FWTDZJG")
    private Double fwtdzjg;

    /**
     * 街道名称
     */
    @Column(name = "JDMC")
    private String jdmc;

    /**
     * 门牌号码
     */
    @Column(name = "MPHM")
    private String mphm;

    /**
     * 东西至
     */
    @Column(name = "DXZ")
    private String dxz;

    /**
     * 相邻小区
     */
    @Column(name = "XLXQ")
    private String xlxq;

    /**
     * 路名
     */
    @Column(name = "LM")
    private String lm;

    /**
     * 片区
     */
    @Column(name = "PQ")
    private String pq;

    /**
     * 仓储面积
     */
    @Column(name = "CCSMJ")
    private Double ccsmj;

    /**
     * 阁楼面积
     */
    @Column(name = "GLMJ")
    private Double glmj;

    /**
     * 车库面积
     */
    @Column(name = "CKMJ")
    private Double ckmj;

    /**
     * 是否普通住房（0否 1是）
     */
    @Column(name = "SFPTZF")
    private Integer sfptzf;

    /**
     * 竣工时间
     */
    @Column(name = "JGSJ")
    private Date jgsj;

    /**
     * 土地用途
     */
    @Column(name = "TDYT")
    private String tdyt;

    /**
     * 土地性质
     */
    @Column(name = "TDXZ")
    private String tdxz;

    /**
     * 分区位置
     */
    @Column(name = "FQWZ")
    private String fqwz;

    /**
     * 规划用途细类
     */
    @Column(name = "GHYTXL")
    private String ghytxl;

    /**
     * 建筑年份
     */
    @Column(name = "JZNF")
    private Integer jznf;

    /**
     * 独用土地面积
     */
    @Column(name = "DYTDMJ")
    private Double dytdmj;

    /**
     * 分摊土地面积
     */
    @Column(name = "FTTDMJ")
    private Double fttdmj;

    /**
     * 分摊建筑面积
     */
    @Column(name = "FTJZMJ")
    private Double ftjzmj;
    /**
     * 采光状况
     */
    @Column(name = "CGZK")
    private String cgzk;

    /**
     * 跃层面积
     */
    @Column(name = "YCMJ")
    private Double ycmj;

    /**
     * 地下室面积
     */
    @Column(name = "DXSMJ")
    private Double dxsmj;

    /* 出租情况
     */
    @Column(name = "CZQK")
    private String czqk;

    /**
     * 地上总层数
     */
    @Column(name = "DSZCS")
    private Integer dszcs;

    /**
     * 是否有电梯
     */
    @Column(name = "SFYDT")
    private String sfydt;

    public String getFwxxid() {
        return this.fwxxid;
    }

    public void setFwxxid(String fwxxid) {
        this.fwxxid = fwxxid;
    }

    public String getBdcdyxxid() {
        return this.bdcdyxxid;
    }

    public void setBdcdyxxid(String bdcdyxxid) {
        this.bdcdyxxid = bdcdyxxid;
    }

    public String getBdcdyh() {
        return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }

    public String getXmmc() {
        return this.xmmc;
    }

    public void setXmmc(String xmmc) {
        this.xmmc = xmmc;
    }

    public String getFwxz() {
        return this.fwxz;
    }

    public void setFwxz(String fwxz) {
        this.fwxz = fwxz;
    }

    public String getFwjg() {
        return this.fwjg;
    }

    public void setFwjg(String fwjg) {
        this.fwjg = fwjg;
    }

    public Integer getSzc() {
        return this.szc;
    }

    public void setSzc(Integer szc) {
        this.szc = szc;
    }

    public Integer getZcs() {
        return this.zcs;
    }

    public void setZcs(Integer zcs) {
        this.zcs = zcs;
    }

    public Integer getWlc() {
        return this.wlc;
    }

    public void setWlc(Integer wlc) {
        this.wlc = wlc;
    }

    public String getFwlx() {
        return this.fwlx;
    }

    public void setFwlx(String fwlx) {
        this.fwlx = fwlx;
    }

    public String getSzmyc() {
        return this.szmyc;
    }

    public void setSzmyc(String szmyc) {
        this.szmyc = szmyc;
    }

    public Double getCg() {
        return this.cg;
    }

    public void setCg(Double cg) {
        this.cg = cg;
    }

    public String getMyzcs() {
        return this.myzcs;
    }

    public void setMyzcs(String myzcs) {
        this.myzcs = myzcs;
    }

    public String getZrzh() {
        return this.zrzh;
    }

    public void setZrzh(String zrzh) {
        this.zrzh = zrzh;
    }

    public String getFjh() {
        return this.fjh;
    }

    public void setFjh(String fjh) {
        this.fjh = fjh;
    }

    public Double getJzmj() {
        return this.jzmj;
    }

    public void setJzmj(Double jzmj) {
        this.jzmj = jzmj;
    }

    public Double getTnmj() {
        return this.tnmj;
    }

    public void setTnmj(Double tnmj) {
        this.tnmj = tnmj;
    }

    public String getGhyt() {
        return this.ghyt;
    }

    public void setGhyt(String ghyt) {
        this.ghyt = ghyt;
    }

    public String getFybh() {
        return this.fybh;
    }

    public void setFybh(String fybh) {
        this.fybh = fybh;
    }

    public String getFwsdswjg() {
        return this.fwsdswjg;
    }

    public void setFwsdswjg(String fwsdswjg) {
        this.fwsdswjg = fwsdswjg;
    }

    public String getFwszdxzqh() {
        return this.fwszdxzqh;
    }

    public void setFwszdxzqh(String fwszdxzqh) {
        this.fwszdxzqh = fwszdxzqh;
    }

    public String getFwszdscjx() {
        return this.fwszdscjx;
    }

    public void setFwszdscjx(String fwszdscjx) {
        this.fwszdscjx = fwszdscjx;
    }

    public String getDlmc() {
        return this.dlmc;
    }

    public void setDlmc(String dlmc) {
        this.dlmc = dlmc;
    }

    public String getXqmc() {
        return this.xqmc;
    }

    public void setXqmc(String xqmc) {
        this.xqmc = xqmc;
    }

    public String getCx() {
        return this.cx;
    }

    public void setCx(String cx) {
        this.cx = cx;
    }

    public String getDyh() {
        return this.dyh;
    }

    public void setDyh(String dyh) {
        this.dyh = dyh;
    }

    public Double getFwtdzjg() {
        return this.fwtdzjg;
    }

    public void setFwtdzjg(Double fwtdzjg) {
        this.fwtdzjg = fwtdzjg;
    }

    public String getJdmc() {
        return this.jdmc;
    }

    public void setJdmc(String jdmc) {
        this.jdmc = jdmc;
    }

    public String getMphm() {
        return this.mphm;
    }

    public void setMphm(String mphm) {
        this.mphm = mphm;
    }

    public String getDxz() {
        return this.dxz;
    }

    public void setDxz(String dxz) {
        this.dxz = dxz;
    }

    public String getXlxq() {
        return this.xlxq;
    }

    public void setXlxq(String xlxq) {
        this.xlxq = xlxq;
    }

    public String getLm() {
        return this.lm;
    }

    public void setLm(String lm) {
        this.lm = lm;
    }

    public String getPq() {
        return this.pq;
    }

    public void setPq(String pq) {
        this.pq = pq;
    }

    public Double getCcsmj() {
        return this.ccsmj;
    }

    public void setCcsmj(Double ccsmj) {
        this.ccsmj = ccsmj;
    }

    public Double getGlmj() {
        return this.glmj;
    }

    public void setGlmj(Double glmj) {
        this.glmj = glmj;
    }

    public Double getCkmj() {
        return this.ckmj;
    }

    public void setCkmj(Double ckmj) {
        this.ckmj = ckmj;
    }

    public Integer getSfptzf() {
        return this.sfptzf;
    }

    public void setSfptzf(Integer sfptzf) {
        this.sfptzf = sfptzf;
    }

    public Date getJgsj() {
        return this.jgsj;
    }

    public void setJgsj(Date jgsj) {
        this.jgsj = jgsj;
    }

    public String getTdyt() {
        return this.tdyt;
    }

    public void setTdyt(String tdyt) {
        this.tdyt = tdyt;
    }

    public String getTdxz() {
        return this.tdxz;
    }

    public void setTdxz(String tdxz) {
        this.tdxz = tdxz;
    }

    public String getFqwz() {
        return this.fqwz;
    }

    public void setFqwz(String fqwz) {
        this.fqwz = fqwz;
    }

    public String getGhytxl() {
        return this.ghytxl;
    }

    public void setGhytxl(String ghytxl) {
        this.ghytxl = ghytxl;
    }

    public Integer getJznf() {
        return this.jznf;
    }

    public void setJznf(Integer jznf) {
        this.jznf = jznf;
    }

    public Double getDytdmj() {
        return dytdmj;
    }

    public void setDytdmj(Double dytdmj) {
        this.dytdmj = dytdmj;
    }

    public Double getFttdmj() {
        return fttdmj;
    }

    public void setFttdmj(Double fttdmj) {
        this.fttdmj = fttdmj;
    }

    public Double getFtjzmj() {
        return ftjzmj;
    }

    public void setFtjzmj(Double ftjzmj) {
        this.ftjzmj = ftjzmj;
    }

    public String getCgzk() {
        return cgzk;
    }

    public void setCgzk(String cgzk) {
        this.cgzk = cgzk;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Double getYcmj() {
        return ycmj;
    }

    public void setYcmj(Double ycmj) {
        this.ycmj = ycmj;
    }

    public Double getDxsmj() {
        return dxsmj;
    }

    public void setDxsmj(Double dxsmj) {
        this.dxsmj = dxsmj;
    }

    public String getCzqk() {
        return czqk;
    }

    public void setCzqk(String czqk) {
        this.czqk = czqk;
    }

    public Integer getDszcs() {
        return dszcs;
    }

    public void setDszcs(Integer dszcs) {
        this.dszcs = dszcs;
    }

    public String getSfydt() {
        return sfydt;
    }

    public void setSfydt(String sfydt) {
        this.sfydt = sfydt;
    }
}
