--liquibase formatted sql
--preconditions dbms:oracle
--changeset BDC_JOB_LOG:1 failOnError:false runOnChange:true runAlways:false
create table BDC_JOB_LOG
(
    ID NUMBER(32) not null,
    JOBGROUP NUMBER(32),
    JOBID NUMBER(32),

    EXECUTORADDRESS VARCHAR2(2000),
    EXECUTORHANDLER VARCHAR2(2000),
    EXECUTORPARAM VARCHAR2(2000),
    EXECUTORSHARDINGPARAM VARCHAR2(2000),
    EXECUTORFAILRETRYCOUNT  NUMBER(32),
    TRIGGERTIME DATE,
    TRIGGERCODE   NUMBER(32),
    TRIGGERMSG VARCHAR2(2000),
    HANDLETIME DATE,
    HANDLECODE  NUMBER(32),
    HANDLEMSG VARCHAR2(2000),
    ALARMSTATUS NUMBER(32)

);

