#读取商品房信息url
fcjy.spf.url:
#读取商品房信息的请求sign值
fcjy.spf.sign:

#读取存量房信息url
fcjy.clf.url:
#读取存量房信息的请求sign值
fcjy.clf.sign:

#通知原登记系统登记状态
ydjxt.djzt.url:

#读取商品房信息url
fcjy.spf2.url: http://www.baidu.com
#读取存量房信息url
fcjy.clf2.url: http://www.baidu.com
#主动扫码下单url
czzf.smxd.url: http://www.baidu.com
#订单撤销url
czzf.ddcx.url: http://www.baidu.com
#订单退款url
czzf.ddtk.url: http://www.baidu.com
#订单查询url
czzf.ddquery.url: http://www.baidu.com
#常州支付-交易通知地址，配置http://ip:port/realestate-exchange/rest/v1.0/interface/ccsf_jgtz
czzf.jgtz.url: http://127.0.0.1:10008/realestate-exchange/rest/v1.0/interface/ccsf_jgtz
#常州支付-终端编号
czzf.zdbh:
#常州支付-终端ip
czzf.zdip:

#常州电子签章地址
zzqz.url: http://127.0.0.1:8080/
# 电子证照 2.0 生成证照「模版配置化接口」
zzqz.mbpzpdf.url: http://127.0.0.1:8080/mbpzpdf
# 电子证照 2.0 电子证照文件下载
zzqz.zzxxxz.url: http://127.0.0.1:8080/zzxxxz
# 电子证照 2.0 电子证照注销
zzqz.zzzx.url: http://127.0.0.1:8080/zzzx
#常州电子签章 token 获取地址
zzqz.token.url: http://127.0.0.1:8080/token
# token 请求参数
zzqz.token.yymc: xxx

#非税收入票据电子化系统
fssr.dzh.url: http://172.18.59.4:8001/fs-gateway/autosyn/h5Data
#6.1.5	缴费办理信息同步接口(data方式)
fssr.jfbltb.method: nontax.payhandle.sync
fssr.jfcx.method: nontax.payaffirm.sync
#固定值
fssr.token: cztoken
fssr.xzqh: 342001

#  票据作废信息同步接口(data方式)
fssr.pjzf.url: http://172.18.59.4:8001/fs-gateway/autosyn/h5Data
fssr.pjzf.method: nontax.eincancel.sync

sw.sfhs.url: http://10.4.250.10:18090/fcjy/qzfw/api/cxywzt

# 易家服务接口
# 预申请推送
yjfw.ysqts.url: http://172.100.201.2:8090/uapws/service/IWarrantMesg
yjfw.ysqts.uri: http://tempuri.org/
yjfw.ysqts.method: getApplyMesg

# 收件材料推送
yjfw.sjclts.url: http://172.100.201.2:8090/uapws/service/IWarrantMesg
yjfw.sjclts.uri: http://tempuri.org/
yjfw.sjclts.method: getFileMesg

sw.soTimeout: 30000

#4.1 资金监管办证凭证查询接口地址
zjj.zjjkbzcx.url: http://IP:8080/ESB/CLF/ZJJG/BZPZ
zjj.zjjkbzcx.token: 0C1BA8CB8D79489E857E875B9E132519
zjj.zjjkbzcx.czry: 张三|34240011
#附件下载接口地址
zjj.fjxz.url: http://IP:8080/ESB/CLF/GJJ/getFile/{fileId}
#上报时审核信息作弊
shxx.one: true
#定时自动上报评价数据任务是否开启
quartz.tspjsj.enable: true
#需要推送评价数据的qxdm集合
tspjsj.qxdmlist: 340101,340104
#定时推送评价数据到省平台时间   // 0 0 20 * * ?    0 0/1 * * * ?
sjpt.tspjsj.cron: 0 0 20 * * ?