#日志相关配置:
log-service:
  #默认使用日志记录方式:未在config中配置的其他地址使用的记录方式。枚举值:logInDb(记录数据库)、logInEs(记录在ES)，不配置则默认使用logInEs
  defaultService: logInDb
  allInEs: true
  #市级采用的日志记录方式
  shijigxRzTypes: logInEs,logInDb
  config:
    #使用logInDb的接口请求地址
    logInDb: -acceptHyxx,-acceptJtcyxx,/realestate-exchange/rest/v1.0/interface/tsSwxxClf,/realestate-exchange/rest/v1.0/interface/tsSwxxSpf,-swCxxx,-swQxzf,-swCxxx,-spfwszt,-swsys,/realestate-exchange/rest/v1.0/interface/getSysAndJkrk,/realestate-exchange/rest/v1.0/hefeisdq/ranqi/ghcx,/realestate-exchange/rest/v1.0/hefeisdq/ranqi/sqgh,/realestate-exchange/rest/v1.0/hefeisdq/dian/ghcx,/realestate-exchange/rest/v1.0/hefeisdq/dian/sqgh,/realestate-exchange/rest/v1.0/hefeisdq/shui/sqgh,
    /realestate-exchange/rest/v1.0/hefeisdq/shui/shuifeicx,-hf_acceptRhcx,-hf_acceptDyswjcrcx,-hf_acceptSiwangxx,-gs_qyxydmcx,/realestate-exchange/rest/v1.0/interface/zjjg_tsdbxx

