# 非税收入票据电子化系统
fssr.dzh.url: http://172.18.59.4:8001/fs-gateway/autosyn/h5Data
# 非税收入票据电子化系统
fssr.dzh.uri: http://172.18.59.4:8001/fs-gateway/autosyn/h5Data
# 缴费办理信息同步接口
fssr.jfbl.method: nontaxPayhandleSync
# 缴费查询（确认）信息同步接口
fssr.jfqr.method: nontaxPayaffirmSync
# 票据作废信息同步接口
fssr.pjzf.method: nontaxEincancelSync
# 电子票据信息同步接口
fssr.dzpj.method: nontaxGeteinvoiceSync

#读取住建局商品房备案信息接口
zjj.spfbaxx.url: http://ip:port/ys_ntzjjg/server/queryBdcHt.do

###水电气
# 第三方水电气过户查询地址
shui.cx.url: https://www.baidu.com/
dian.cx.url: https://www.baidu.com/
qi.cx.url: https://www.baidu.com/
#第三方水电气过户接口地址
shui.gh.url: https://www.baidu.com/
dian.gh.url: https://www.baidu.com/
qi.gh.url: https://www.baidu.com/
#淮安淮阴区水过户接口地址
hy.shui.gh.url: https://www.baidu.com/
#淮安淮阴区水过户秘钥
hy.shui.gh.secretkey: hyzls

# ems下单取号地址
ems.xdqh.url: https://10.203.199.13:2380/iwaybillno-web/a/iwaybill/receive
# ems电商标识
ems.dsbs: XYD
# ems客户代码
ems.senderNo: 1100136137609
# ems签名
ems.secrectkey: 70712a0ef629959f1365788e34752db6