#连云港
#摩科评价接口地址
mk.evaluate.url.340104: http://服务器ip:端口号/pad/pjscRequest1111
#登记系统发起人证比对接口
mk.facevalidateWithidCard.url.340104: http://服务器ip:端口号/pad/rzbdRequest1111
#登记系统发起签名接口
mk.sendtxqm.url.340104: http:// 服务器ip:端口号/pad/name/sign/sendTxQm1111

#自动触发评价结果数据
mk.sendProv.url.340104: http:// 服务器ip:端口号/pad/name/sign/sendTxQm1111

#摩科qrcode1配置地址
mk.qrcode1Url:
#摩科qrcode是否拼接
mk.qrcodepj: