#intercept:
#  tries:
#    limit:
#      hlwj:
#        path: /realestate-exchange/rest/v1.0/**
#        ignore: /**
#        trytimes: 10
#        trytime: 3
#      wwsq:
#        path: /realestate-exchange/rest/v1.0/**
#        ignore:
#        trytimes:
#        trytime: