#合肥接口房产交易应用标识码
fcjy.appCode: ea7acbe1aa484f0daea3da7fc5356e13
#房产交易 限购验证接口请求地址
fcjy.xgxx.url: http://200.1.1.168:8030/api/LimitPurch/Search
#房产交易 存量房合同读取接口请求地址
#fcjy.htxx.url: http://200.1.1.168:8030/api/LocalTaxBureau/SearchStockHouseContract
#房产交易 根据产权证号和权利人证件号读取存量房备案信息接口请求地址
fcjy.baxx.url: http://200.1.1.168:8030/api/LocalTaxBureau/SearchStockHouseContracts


#合肥商品房备案信息接口httpURL
spf.baxx.url: http://www.baidu.com
#合肥商品房备案信息接口易应用标识码
spf.appCode: 123456

#税务机构代码
sw.swjgdm: 13401023200
sw.channelid: AHHFBDC
sw.token: GJSWZJAHSSWJ

# 税务推送附件URL
sw.tsfjcl.url: http://59.203.19.50:8280/YTHFcjyEstate/external/doService

# 税务验证完税状态 接口地址
sw.spfwszt.url: http://59.203.19.50:8280/YTHFcjyEstate/external/doService

#税务 存量房信息推送
sw.clfxx.url: http://59.203.19.50:8280/YTHFcjyEstate/external/doService

#税务 商品房信息推送
sw.zlfxx.url: http://59.203.19.50:8280/YTHFcjyEstate/external/doService

#税务 申报取消作废接口地址
sw.qxzf.url:  http://59.203.19.50:8280/YTHFcjyEstate/external/doService

#税务 查询信息接口地址
sw.cxxx.url:  http://59.203.19.50:8280/YTHFcjyEstate/external/doService

#税务 土地契税采集接口
sw.sc_tdqscj.url: http://59.203.19.50:8280/YTHFcjyEstate/external/doService


#家庭成员 查询信息接口地址
jtcy.cxxx.url: http://www.baidu.com
#家庭查询的公开查询配置
jtcy.openapi.appkey: 10001024
jtcy.openapi.username: sgtj_yanghong
jtcy.openapi.skprivateKeyFile.path: D:\\openApi.pem


#工商对接接口
gs.qyxydmcx.url: http://200.1.1.176:8080/openapi/rest/1.0/lgl_comb_cmp_base_info_yyzz
gs.qyzxyz.url: http://200.1.1.176:8080/openapi/rest/1.0/md_qyzx_hy
#工商的公开查询配置
gs.openapi.appkey: 10001024
gs.openapi.username: sgtj_yanghong
gs.openapi.skprivateKeyFile.path: D:\\openApi.pem

#民政 获取配偶信息
mz.hyxx.url: http://200.1.1.176:8080/openapi/rest/1.0/bdc_md_jhxx_lhxx_poxx
#民政的公开查询配置
openapi.appkey: 10001034
openapi.username: sgtj_yanghong
openapi.skprivateKeyFile.path: D:\\openApi.pem
# 机关单位法人信息查询URL
openapi.jgdwfrxx.url: http://10.33.1.48:10032/openapi/rest/1.0/bdc_jgdw_xxcx

#死亡信息查询URL
openapi.siwangxx.url: http://10.33.1.48:10032/openapi/rest/1.1/is_bdc_czrkjbxxb

#社会组织_事业单位_机关团体融合查询接口URL
openapi.rhcx.url: http://10.33.1.48:10032/openapi/rest/1.1/is_bdc_shzzjbxx

#融资担保_小额贷款公司信息查询
openapi.rzdbgscx.url: http://10.33.1.48:10032/openapi/rest/1.1/is_bdc_rzdbgsxx

#第一顺位继承人查询URL
openapi.dyswjcr.url: http://10.33.1.48:10032/openapi/rest/1.1/is_bdc_parent

#小微企业信息查询
openapi.xwqycx.url: http://10.33.1.48:10032/openapi/rest/1.0/CBIS_TrdMicro

# 合肥省级查询 IP 和端口
sdkapi.host: 200.1.1.168
sdkapi.httpPort: 8030




#合肥档案信息
daxx.url: http://200.1.1.219:8097/ServiceSplitImage.asmx
daxx.uri: http://tempuri.org/
#合肥档案接口 基本信息接口方法名
daxx.jbxx.method: HeFeiImgFileId
#合肥档案接口 目录信息接口方法名
daxx.mlxx.method: GetArchContent
#分户图目录接口 目录信息接口方法名
daxx.fcfhtmlxx.method: GetArchContent_fht
#合肥档案接口 读取档案的附件URL
daxx.fjxx.url: http://200.1.1.219:8097/ServiceSplitImage.asmx/GetArchImgFile
#合肥档案接口传输头信息定义：http contentType xml
http.content.type.xml: text/xml; charset=UTF-8
#分户图目录接口 目录信息接口方法名
daxx.fcfht.url: http://200.1.1.219:8097/ServiceSplitImage.asmx/GetArchContent_fht

#省级平台 请求基础配置
sjpt.xzqdm: 123456
sjpt.username: gx123456
sjpt.password: 4963908eaa34eb2107f519b8dd298188
sjpt.cxjgbs: bdcdj
#省级平台获取token路径
sjpt.token.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/bdc/token
#省级平台获取验证openid有效性路径
sjpt.checkopenid.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/bdc/credential/{openid}
#省级平台超时设置 毫秒
sjpt.soTimeout: 360000

# 2.1公安部-身份核查服务接口url
sjpt.police.identityCheck.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 2.3民政部-婚姻登记信息查询服务接口url:
sjpt.civil.marriageQuery.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 2.5银保监会-金融许可证查询接口url:
sjpt.cbirc.financialQuery.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 2.6中编办-事业单位登记信息（含机关、群团信息）查询接口url
sjpt.scopsr.organQuery.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 2.7 最高法-司法判决信息查询申请接口url
sjpt.supremecourt.decisionApply.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 2.8最高法-司法判决信息结果反馈接口url
sjpt.supremecourt.decisionResponse.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 3.9 市场监管总局-企业基本信息验证接口url
sjpt.zw.samr.enterpriseCheck.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 2.1公安部-身份核查服务接口 登记部门统一信用代码
sjpt.bus_sre_deptcode: 123456

#推送区县上报销账数据
sjpt.qxxz.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/consistency/report-write-off


#省级平台查询接入分数
sjpt.zlpf.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/bdc/query/quality-score
sjpt.zlpf.soTimeout: 8000
#省级平台查询文书下发接口地址
sjpt.cxws.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/bdc/query/receive/doc
#省级平台查询结果接口地址
sjpt.cxjg.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/bdc/query/commit/result
#省级平台查询申请接口地址
sjpt.cxsq.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/bdc/query/receive/apply
#省级平台查询申请接口超时时间
sjpt.cxsq.soTimeout: 8000
#省级平台查询申请反馈接口地址
sjpt.cxsqfk.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/bdc/query/commit/apply

#省级平台相关查询婚姻信息接口地址
xgbmcx.hyxx.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#省级平台相关查询社会组织信息接口地址
xgbmcx.shgx.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#省级平台相关查询居民身份信息查询接口
xgbmcx.jmsf.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#省级平台相关查询居民身份信息反馈查询接口
xgbmcx.jmsfsqfk.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#省级平台相关查询企业信息查询接口
xgbmcx.qyxx.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#省级平台相关查询户籍信息查询申请接口
xgbmcx.hjxxcxsq.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#省级平台相关查询户籍信息查询申请反馈接口
xgbmcx.hjxxcxfk.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply

#江苏省级平台-2.2 民政部-地名信息查询接口
jiangsu.mzb.dmxxcx.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply

#2.4 民政部-社会组织统一社会信用代码信息查询服务接口
jiangsu.mzb.shzztyxydm.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply

# 3.1 卫健委-出生医学证明查询接口
jiangsu.mzb.jrxkz.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#  3.2 卫健委-死亡医学证明查询接口
jiangsu.mzb.swyxzm.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 3.3 民政部-基金会法人登记证书查询接口
jiangsu.mzb.jjhfrdjzs.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 3.4 民政部-民办非企业单位登记证书查询接口
jiangsu.mzb.mbfqydjzs.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#3.5 民政部-社会团体法人登记证书查询接口
jiangsu.mzb.shttfrdjzs.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
# 3.6 民政部-婚姻登记信息核验（个人）接口
jiangsu.mzb.hyxxhygr.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#3.7 民政部-婚姻登记信息核验（双方）接口
jiangsu.mzb.hyxxhysf.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#3.10  中编办-党群机关信息查询接口
jiangsu.mzb.dqjg.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply
#3.11 中编办-事业单位信息查询接口
jiangsu.mzb.sydw.url: http://10.0.0.6:8090/realestate-supervise-exchange/api/v1/other-subject/query/apply



#国图大云文件中心URL
gtdy.file.url: http://192.168.10.87:8019/storage/rest/files/download


# 省级平台定时任务配置
sjpt:
  # 定时获取 查询申请条件
  cxsq:
    #开关
    switch: false
    #cron表达式
    cron: 0 */2 * * * ?

  # 定时查询结果
  queryCxjg:
    switch: false
    cron: 0 */5 * * * ?

  # 提交查询结果
  commitCxjg:
    switch: false
    cron: 0 */3 * * * ?

  # 单权利人多产权批量处理方案
  sjplcl: true

#南通存量房合同信息服务地址
nt.clfhtxx.url: http://www.baidu.com

#一窗受理验证完税状态接口地址
ycsl.hszt.url: http://www.baidu.com
# 退件请求接口地址
ycsl.tjqq.url: http://www.baidu.com

#外网 删除任务
wwsq.deletetask.url: ${app.portal-ui}/rest/v1.0/workflow/process-instances


#南通自助查询机有房无房查询配置
#流水号中的区位码，不配置则流水号中无区位码
zfcx.lshqwm: 07
#流水号位数配置，默认6位
zfcx.lshws: 6
#无房查询编号生成样例,${nf}代表查询年份，${qwm}代表区位码，${lsh}代表流水号，这3个参数必须要，其余汉字部分可随意配置修改,默认为‘公开${nf}区号${qwm}${lsh}’
#如果不想显有房无房，行政区号，则直接配置此处的value为："value":"${nf}${lsh}"，此时显示的编号为年份加6为流水号，例如2017000002
#有房流水号模板
zfcx.yflshExample: 有房{nf}区号{qwm}{lsh}
#无房流水号模板
zfcx.wflshExample: 无房{nf}区号{qwm}{lsh}
#房屋权属查询流水号模板
fwqs.lshExample: 公开{nf}区号{qwm}{lsh}
#合肥 房产交易根据FWBM查预查封数据接口
fcjy.ycfbyfwbm.url: http://200.1.1.168:8030/api/NewHouse/GetSeals

#部级接口
#婚姻登记信息接口地址
bjjk.hydjxx.url: http://10.255.203.141:8080/register/api/IDServices
#社会组织统一信用代码信息
bjjk.shzz.url: http://10.255.203.141:8080/register/api/IDServices
#金融许可证查询
bjjk.jrxkz.url: http://10.255.203.141:8080/register/api/IDServices
#中编办查询接口
bjjk.zbb.url: http://10.255.203.141:8080/register/api/IDServices
#司法判决查询
bjjk.sfpjcx.url: http://10.255.203.141:8080/register/api/IDServices
#司法判决反馈查询
bjjk.sfpjcxfk.url: http://10.255.203.141:8080/register/api/IDServices
#地名信息查询
bjjk.dmxxcx.url: http://10.255.203.141:8080/register/api/IDServices

# 公安身份核查 请求地址
bjjk.gasfhc.url: http://10.255.203.141:8080/register/api/IDServices
# 公安身份核查 部门编码
bjjk.gasfhc.deptcode: BDCDJ

#部级接口 请求token
bjjk.token: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBmeVa_KHCbYL1fRczTI3eExX5uVv0-6fKxkVD0gkrMaFV5XDfbrhz4emgo8fmwWSnZlUyrtvPpZ6wg6MVlC98lIIH-6t1gyBKQlnlF8jIUEqvIgnvrP9dxWqy12elbsLAKHjGrckz6Ul9lK6CXNs7hMm2QbxZsdBWLJloxC_3aQIDAQAB
#部级接口 用户ID
bjjk.id: ce562f29ffbd420e89f70c33140a8e68
#部级接口 登记部门名称
bjjk.deptName: 合肥市不动产登记局
#部级接口 行政区划
bjjk.xzqh: 340100

#安徽省厅接口
#安徽省厅接口 调用地址
ahst.url: http://11.48.0.49:9905/transit/api/getApiInfo
#安徽省厅接口 调用部门
ahst.deptName: 安徽省自然资源厅
#安徽省厅接口 行政区划
ahst.xzqh: 340000
#安徽省厅接口 token
ahst.token: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQdg7PXA7iBtqJvGghcKa3Xki2Ya0tcXqpHaAV8JJ6NhO8JawVOGhhr2xOvhLS2WUNWP4JnZ1ILfRxINrm5_ivebgds7VahUyrTrJNgzB3J9NPTP4Gb_A11L8nyP_FRjCd9eXiHDysSTk91KePSb792EHkXFD1tz8QDneWSnoZQwIDAQAB

#安徽省厅身份核查接口 登记部门统一信用代码
ahst.sfhc.deptcode: 123400007568124200
#安徽省厅身份核查接口 操作人所在单位地址
ahst.sfhc.deptaddr: 安徽省自然资源信息中心（安徽省地质资料馆）
#安徽省厅身份核查接口 应用名称
ahst.sfhc.appname: 测试系统
#安徽省厅身份核查接口 业务类型代码
ahst.sfhc.businesstypecode: SC000023
#安徽省厅身份核查接口 业务类型名称
ahst.sfhc.businesstypename: 首次登记

# 发送信息客户端
msg.center.clientId: bpmInstance

#通用创建接口配置自动办结工作流定义id集合
initwwsq:
  zdbjlist: 多个用,分割DjNRWsrc6DwetKTF
  zdbjslr: 单个指定人员用户名


#更新制证状态 -德宽版本url
dksw.gxzz.url: https://www.baidu.com
#德宽税务存量房url
dksw.clfxx.url: https://www.baidu.com
#请求头token
dksw.token: eyJhbGciOiJIUzI1NiJ9.eyJDSEFOTkVMX0lEIjoiQUguVEFYLkJEQ0pZLkhCIiwiaWF0IjoxNTc3NDQ0MjY1LCJleHAiOjE2MDc0MzAyNjV9.UtrIRBhCFbA5Oqnv2i-483TdB2Q3j6iifyQTj8Lfb0c
#请求头用户名密码
dksw.expandName: 1340HFBDCJY
dksw.expandPwd: 1340HFBDCJY
dksw.author: 合肥不动产
#推送税务附件
dksw.tsfjcl.url: https://www.baidu.com
#德宽税务channelid
dksw.channelid: AH.TAX.BDCJY.XX
#德宽税务增量房url
dksw.zlfxx.url: https://www.baidu.com
#德宽查询税务url
dksw.cxxx.url: https://www.baidu.com
#德宽取消作废税务url
dksw.qxzf.url: https://www.baidu.com
#德宽查询税务三要素url
dksw.swsys.url: https://www.baidu.com
#德宽查询税务三要素版本，yt:英塔否则德宽
ykq.swsys.version:
#德宽查询完税信息url
dksw.wsxx.url: https://www.baidu.com
#获取税务支付连接
dksw.zflj.url: https://www.baidu.com
#获取税务支付状态
dksw.zfzt.url: https://www.baidu.com

#安徽德宽税务推送土地契税使用：出让方名称
dksw.tdqs.crfmc: 舒城县不动产登记中心
#安徽德宽税务推送土地契税使用：出让方证件号码
dksw.tdqs.crfzjhm: 23232323

#国网电力接口配置
#分配的appId
guojiadianwang.dian.appId: testApp
#私钥
guojiadianwang.dian.secret: testSecret123456
guojiadianwang.dian.rasPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD0dxq1W8t3rAmZSHRLAddGAWtX5wlDdtLXHoC5MUkXO6EFO/b+z+8jPfqxr4hgnnPseIM7qRx78sEKfI0iu/HzbfBz7uctF5+PU9m7axYfpHDHrl/59bdHBXiIA9/9UMcy+3aDEU6B4lnkhrJWD8OLUOrgWuy/uaQmGB3Dm0m6wwIDAQAB
#是否需要请求头
guojiadianwang.dian.needHead: false
#1、国家电网不动产调用供电公司推送房产过户用户接口
guojiadianwang.dian.push.url: http:// 59.203.236.100:9921/api/push
#2、	国家电网不动产调用供电公司推送房产过户图片附件
guojiadianwang.dian.attach.url: http:// 59.203.236.100:9921/api/attachImage
#3、	国家电网不动产调用供电公司数据删除接口
guojiadianwang.dian.delete.url: http:// 59.203.236.100:9921/api/delete
#4、	国家电网不动产调用供电公司过户办理情况查询
guojiadianwang.dian.getResult.url: http:// 59.203.236.100:9921/api/getResult
#5、	国家电网不动产调用供电公司验证是否欠费
guojiadianwang.dian.preVarify.url: http:// 59.203.236.100:9921/api/preVarify

#向互联网查询缴费信息url
wwsq.jfxxcx.url: http://www.baidu.com

#4.1.7获取第三方接入token
wwsq.token.url: http://www.baidu.com

#4.2.1	预约查询
wwsq.yycx.url: http://www.baidu.com

#4.2.10	预约确认到场
wwsq.yyqr.url: http://www.baidu.com
#互联网提供的用户名和密码
wwsq.username:
wwsq.userpwd:

#抵押预抵押信息查询产权类型集合
dyxxandydyxx.xmcqqllx: 4,6,8

#个人档案查询是否查询土地信息
grdacx.queryJsyd: false

#查询预告预抵押接口，是否置空权利人类别参数
getYgxx.zkqlrlb: true
#是否取szc参数
getwwsqcqzxx.szc: true