#大数据局接口通用配置：
#终端地址
gspapi.url: http://59.203.64.16:8000
#应用编码 3403-XXXX
gspapi.yybm:
#授权码 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
gspapi.sqm:
#用户名
gspapi.username: bbsg
#密码
gspapi.password: 913fdd2942b4f91ce6dc3d2feb76aa63
#客户端信息 zzwk_sgtzyj
gspapi.clientInfo: zzwk_sgtzyj
#身份证信息 接口编码
gspapi.sfzxx.jkbm: 3403-0041-1-00000007
#身份证信息 服务编码 340300000000_01_XXXXXXXXXX
gspapi.sfzxx.serviceCode: 340300000000_01_0000010518

#营业执照信息 接口编码
gspapi.yyzzxx.jkbm: 3403-0041-1-00000008
#营业执照信息 服务编码 340300000000_01_XXXXXXXXXX
gspapi.yyzzxx.serviceCode: 340300000000_01_0000010519

#婚姻状况信息 接口编码
gspapi.hyzkxx.jkbm: 3403-0041-1-00000003
#婚姻状况信息 服务编码 340300000000_01_XXXXXXXXXX
gspapi.hyzkxx.serviceCode: 340300000000_01_0000010385

#户籍状况信息 接口编码
gspapi.hjxx.jkbm: 3403-0041-1-00000004
#户籍状况信息 服务编码 340300000000_01_XXXXXXXXXX
gspapi.hjxx.serviceCode: 340300000000_01_0000010383

#出生信息 接口编码
gspapi.csxx.jkbm: 3403-0041-1-00000050
##出生信息 接口编码 服务编码 340300000000_01_XXXXXXXXXX
gspapi.csxx.serviceCode: 340300000000_01_0000010673

#死亡信息 接口编码
gspapi.swxx.jkbm: 3403-0075-1-00000006
##死亡信息 接口编码 服务编码 340300000000_01_XXXXXXXXXX
gspapi.swxx.serviceCode: 340300000000_01_0000010728
#土地资产划拨 接口编码
gspapi.tdzchb.jkbm: 3403-0075-1-00000006
##土地资产划拨 接口编码 服务编码 340300000000_01_XXXXXXXXXX
gspapi.tdzchb.serviceCode: 340300000000_01_0000010728

fcjy.ht.url: http://11.48.90.138:8005/WcfLib?wsdl
fcjy.ht.uri: http://tempuri.org/
fcjy.ht.method: DoAsk

#蚌埠国网电力接口配置
#分配的appId
bengbu.dian.appId: testApp
#私钥
bengbu.dian.secret: testSecret123456
bengbu.dian.rasPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD0dxq1W8t3rAmZSHRLAddGAWtX5wlDdtLXHoC5MUkXO6EFO/b+z+8jPfqxr4hgnnPseIM7qRx78sEKfI0iu/HzbfBz7uctF5+PU9m7axYfpHDHrl/59bdHBXiIA9/9UMcy+3aDEU6B4lnkhrJWD8OLUOrgWuy/uaQmGB3Dm0m6wwIDAQAB
#2、蚌埠不动产调用供电公司推送房产过户用户接口
bengbu.dian.push.url: http://23.50.167.78:18080/api/push
#3、	蚌埠不动产调用供电公司推送房产过户图片附件
bengbu.dian.attach.url: http://23.50.167.78:18080/api/attach
#4、	蚌埠不动产调用供电公司数据删除接口
bengbu.dian.delete.url: http://23.50.167.78:18080/api/delete

#蚌埠供气接口配置
#分配的appId
bengbu.qi.appId: testApp
#私钥
bengbu.qi.secret: testSecret123456
bengbu.qi.rasPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqpvlWpHk9nHSXXZTIjWiVAC4iDRCMCAnbbIJvp7uRbvjoKEGAwxNnCXBBuQWLXEVTaJ+b60nS1ogbT8h489Pt0nA1NAOZLq1JeOU8sOYoP+aZc3XvS8Z6gQT1NY0xMqDW0KbjPK91l6G6iRdfvb2LKXGqhurvSTV1c87fXkV7VQIDAQAB
#2、蚌埠不动产调用供气公司推送房产过户用户接口
bengbu.qi.push.url: http://36.7.136.119:9088/gas/api/push
#4、	蚌埠不动产调用供气公司数据删除接口
bengbu.qi.delete.url: http://36.7.136.119:9088/gas/api/delete


#蚌埠供水接口
#1、蚌埠不动产调用供水公司获取token
bengbu.shui.token.url: http://218.22.88.141:35202/workflow/api/appService/getToken
#2、蚌埠不动产调用供水公司推送房产过户用户接口
bengbu.shui.push.url: http://218.22.88.141:35202/workflow/api/appService/createData
#3、蚌埠不动产调用供水公司推送房产过户图片附件
bengbu.shui.attach.url: http://218.22.88.141:35202/workflow/api/appService/createFileData
#4、蚌埠不动产调用供水公司数据删除接口
bengbu.shui.delete.url: http://218.22.88.141:35202/workflow/api/appService/deletData

# 是否开启监听外网申请FTP压缩文件进行创件功能
bengbu.wwsqftp.enable: false
# 定时监听FTP文件目录下是否有新增的申请文件，默认一分钟监听一次
bengbu.wwsqftp.cron: 0 */50 * * * ?
# 外网申请FTP压缩文件存放服务器 IP username password port
bengbu.wwsqftp.ip: 192.168.2.86
bengbu.wwsqftp.username: FtpAdmin
bengbu.wwsqftp.password: Gtmap123
bengbu.wwsqftp.port: 21
# 外网申请FTP压缩文件在FTP服务器存放路径
bengbu.wwsqftp.ftpFilePath: test
# 登记处理完成后FTP文件移动到已完成目录路径
bengbu.wwsqftp.hasResolvedFtpFilePath: old
# 登记创件完成返回信息文件在FTP服务器存放路径
bengbu.wwsqftp.responseFilePath: response
# 登记文件操作缓存目录（可以配置和打印一个路径）
bengbu.wwsqftp.dengji.filepath: D:\\var
# 文件编码方式，默认GBK
bengbu.wwsqftp.encoding: GBK
# 查封登记查询的权利类型
getWwsqcfCqzxxFy.qllx: 3,4,5,6,7,8

#蚌埠政务取号地址和端口配置项
bengbu.zwip: 11.48.64.75
bengbu.zwport: 37812


# 省金融平台，不动产登记注册公钥
sjrpt.bdcgy: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAE/BPPhl9Mtoul7s64cOI3xRnE+5ZBh2hZ2A7g10vaLOdYhYg3Bn7492x6wIteziq9GKujNijKB2LJOcjxlTqb6w==
# 省金融平台，不动产登记注册私钥
sjrpt.bdcsy: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgHBdUGj7fKF5dObKfw+GD0gx/7+ybMTCHtsoHt9lMdJ+gCgYIKoEcz1UBgi2hRANCAAT8E8+GX0y2i6Xuzrhw4jfFGcT7lkGHaFnYDuDXS9os51iFiDcGfvj3bHrAi17OKr0Yq6M2KMoHYsk5yPGVOpvr

#省金融服务平台，驳回互联网申请url
sjrpt.bhhlwsq.url: http://www.baidu.com
#省金融服务平台，推送EMS信息url
sjrpt.tsems.url: http://www.baidu.com
# 省金融平台公钥请求地址
sjrpt.gy.url: http://www.baidu.com
#省金融平台规则验证接口的对照，1对照抵押创建的工作流定义id，2对照抵押注销的工作流定义id
sjrpt.gzyz.gzldyidmap: "{'1':'DXKYRaGMj8bedSCy','2':'DXKYRaGMj8bedSCy'}"

#提供测绘成果的分类查询
chcg.flcx.url: www.baidu.com
#蚌埠多测合一提供  土地出让接口
dchy.tdcr.url: http://59.203.59.124:8889/bbcggl/queryTdcrList.hebe
#蚌埠多测合一提供  土地划拨接口
dchy.tdhb.url: http://59.203.59.124:8889/bbcggl/queryTdcrList.hebe
#蚌埠多测合一提供  建设用地规划许接口
dchy.jsytghxk.url: http://59.203.59.124:8889/bbcggl/queryTdcrList.hebe
#蚌埠多测合一提供  建设工程规划许可接口
dchy.jsgcghxk.url: http://59.203.59.124:8889/bbcggl/queryTdcrList.hebe
#蚌埠多测合一提供  建设工程规划核实接口
dchy.jsgcghhs.url: http://59.203.59.124:8889/bbcggl/queryTdcrList.hebe
#工程审批系统-通知工程审批系统审批完成
gcsp.receive.url: http://59.203.63.189:7050/aplanmis-rest/rest/building/receive
#工程审批系统-电子证照接收接口
gcsp.tsdzzz.url: http://59.203.63.189:7050/aplanmis-rest/rest/building/receiveLicence
#好差评评价页面接口地址
hcp.pjym.url: http://IP:PORT/bog-evaluate-pad/ipadView?key=
#好差评更新状态接口地址
hcp.gxzt.url: http://59.203.166.77:8809/bog-evaluate-local/hcp/updateEvaluateStatus
#好差评讯飞地址
hcp.xf.url: http://ip:port/smartdev-rest/msg/push.do
#好差评讯飞的msgcode配置
hcp.xf.msgcode: PJQ_004_000001
#好差评讯飞的msgtype配置
hcp.xf.msgtype: 900