--liquibase formatted sql
--preconditions dbms:oracle
--changeset BDC_SL_JCGG:1 failOnError:false runOnChange:true runAlways:false

CREATE TABLE BDC_SL_JCGG
  (
    GGID  VARCHAR2(32) NOT NULL,
    GZLSLID  VARCHAR2(32),
    JCR    VARCHAR2(200),
    BJCR VARCHAR2(200),
    ZL   VARCHAR2(500),
    GGKSSJN VARCHAR2(10),
    GGKSSJY VARCHAR2(10),
    GGKSSJR VARCHAR2(10),
    GGJSSJN VARCHAR2(10),
    GGJSSJY VARCHAR2(10),
    GGJSSJR VARCHAR2(10),
    constraint BDC_SL_JCGG primary key(GGID)
);
comment on table BDC_SL_JCGG
  is '不动产受理继承公告';
COMMENT ON COLUMN BDC_SL_JCGG.GGID IS '公告id';
COMMENT ON COLUMN BDC_SL_JCGG.GZLSLID IS '工作流实例ID';
COMMENT ON COLUMN BDC_SL_JCGG.JCR IS '继承人';
COMMENT ON COLUMN BDC_SL_JCGG.BJCR IS '被继承人';
COMMENT ON COLUMN BDC_SL_JCGG.ZL IS '坐落';
COMMENT ON COLUMN BDC_SL_JCGG.GGKSSJN IS '公告开始时间年';
COMMENT ON COLUMN BDC_SL_JCGG.GGKSSJY IS '公告结束时间月';
COMMENT ON COLUMN BDC_SL_JCGG.GGKSSJR IS '公告开始时间日';
COMMENT ON COLUMN BDC_SL_JCGG.GGJSSJN IS '公告结束时间年';
COMMENT ON COLUMN BDC_SL_JCGG.GGJSSJY IS '公告开始时间月';
COMMENT ON COLUMN BDC_SL_JCGG.GGJSSJR IS '公告结束时间日';
CREATE INDEX "BDC_SL_JCGG_INDEX_GZLSLID" ON BDC_SL_JCGG (GZLSLID);