info:
  name: ${spring.application.name}
  component: Portal UI Application

app:
  center: http://192.168.2.151:8000/eureka/
  oauth: http://192.168.2.151:8002/account
  security:
    moduleAuthPath: http://account/account
    ignores: /image/**,/css/**,/js/**,/webjars/**
    authorities:
      permitAll:
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated: true
    resources:
      authenticated: /realestate-portal-ui/rest/v1.0/**,/rest/v1.0/check/feign/gzyz/**

spring:
  rabbitmq:
    host: 192.168.0.60
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 192.168.0.60
  profiles:
    include: params,simple
  messages:
    basename: messages
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  zipkin:
    # base-url: http://localhost:8003
    sender:
      type: rabbit
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: ${port:8567}
  servlet:
    context-path: /realestate-portal-ui
  session:
    timeout: 3600

logging:
  classify:
    # 表示除path之外的路径下默认的日志分类为platform
    defaulted: platform
#    /rest/**, /test/** 路径下的日志分类为 test， 如果不需要可以不配做
#    path:
#      test: /rest/**, /test/**
