package cn.gtmap.realestate.etl.core.domian.ycsl;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Thu Aug 02 16:19:23 CST 2018.</p>
 *
 * @author huangzijian
 */

@Entity
@Table(name = "YCSL_JYXX")
public class YcslJyxxDo implements Serializable {

    private static final long serialVersionUID = 6250439872790873094L;

    /**
     * 主键
     */
    @Column(name = "JYXXID")
    @Id
    private String jyxxid;
    /**
     * 项目编号
     */
    @Column(name = "XMBH")
    private String xmbh;
    /**
     * 合同编号
     */
    @Column(name = "HTBH")
    private String htbh;
    /**
     * 合同状态 0：未备案1：备案2：解约
     */
    @Column(name = "HTZT")
    private String htzt;
    /**
     * 合同备案号
     */
    @Column(name = "HTBAH")
    private String htbah;
    /**
     * 交易金额
     */
    @Column(name = "JYJE")
    private Double jyje;
    /**
     * 单价
     */
    @Column(name = "DJ")
    private Double dj;
    /**
     * 合同登记时间
     */
    @Column(name = "HTDJSJ")
    private Date htdjsj;
    /**
     * 合同备案时间
     */
    @Column(name = "HTBASJ")
    private Date htbasj;
    /**
     * 数据归属地区
     */
    @Column(name = "SJGSDQ")
    private String sjgsdq;
    /**
     * 备注
     */
    @Column(name = "BZ")
    private String bz;
    /**
     * 项目id
     */
    @Column(name = "PROID")
    private String proid;
    /**
     * 合同金额
     */
    @Column(name = "HTJE")
    private Double htje;
    /**
     * 首付金额
     */
    @Column(name = "SFJE")
    private Double sfje;
    /**
     * 贷款金额
     */
    @Column(name = "DKJE")
    private Double dkje;
    /**
     * 监管金额
     */
    @Column(name = "JGJE")
    private Double jgje;
    /**
     * 银行代码（SWIFT码前8位）
     */
    @Column(name = "YHDM")
    private String yhdm;
    /**
     * 监管账户开户行
     */
    @Column(name = "JGZHKHH")
    private String jgzhkhh;
    /**
     * 监管账户号
     */
    @Column(name = "JGZHH")
    private String jgzhh;
    /**
     * 监管账户名
     */
    @Column(name = "JGZHM")
    private String jgzhm;
    /**
     * 权属转移对象
     */
    @Column(name = "QSZYDX")
    private String qszydx;
    /**
     * 权属转移方式
     */
    @Column(name = "QSZYFS")
    private String qszyfs;
    /**
     * 权属转移用途
     */
    @Column(name = "QSZYYT")
    private String qszyyt;
    /**
     * 成交价格是否含税
     */
    @Column(name = "CJJGSFHS")
    private String cjjgsfhs;
    /**
     * 是否差额征收
     */
    @Column(name = "SFCEZS")
    private String sfcezs;
    /**
     * 是否共有人打票
     */
    @Column(name = "SFGYRDP")
    private String sfgyrdp;
    /**
     * 个人所得税扣除成本及合理费用
     */
    @Column(name = "SDSKC")
    private Double sdskc;
    /**
     * 本次申报交易是否属于转让方自开票
     */
    @Column(name = "SBJYSFSZZR")
    private String sbjysfszzr;
    /**
     * 交易抵扣金额
     */
    @Column(name = "JYDKJE")
    private Double jydkje;
    /**
     * 当期应收税款所属月份
     */
    @Column(name = "SKSSYF")
    private String skssyf;
    /**
     * 登记注册类型
     */
    @Column(name = "DJZCLX")
    private String djzclx;
    /**
     * 上手价格
     */
    @Column(name = "SSJG")
    private Double ssjg;
    /**
     * 相邻小不动产项目编号
     */
    @Column(name = "BDCXMBH")
    private String bdcxmbh;
    /**
     * 交易类型
     */
    @Column(name = "JYLX")
    private String jylx;
    /**
     * 备案金额
     */
    @Column(name = "BAJE")
    private Double baje;
    /**
     * 上次取得房屋时间
     */
    @Column(name = "SCQDFWSJ")
    private Date scqdfwsj;
    /**
     * 是否代收土地收益金
     */
    @Column(name = "SFDSTDSYJ")
    private String sfdstdsyj;
    /**
     * 房产证发证时间
     */
    @Column(name = "FCZFZSJ")
    private Date fczfzsj;
    /**
     * 购房发票取得时间
     */
    @Column(name = "GFFPQDSJ")
    private Date gffpqdsj;
    /**
     * 原购房契税完成时间
     */
    @Column(name = "GFQSWCSJ")
    private Date gfqswcsj;
    /**
     * 不含增值税金额
     */
    @Column(name = "BHZZSJE")
    private Double bhzzsje;
    /**
     * 增值税金额
     */
    @Column(name = "ZZSJE")
    private Double zzsje;
    /**
     * 含增值税金额
     */
    @Column(name = "HZZSJE")
    private Double hzzsje;
    /**
     * 付款方式
     */
    @Column(name = "FKFS")
    private String fkfs;
    /**
     * 印花税减半
     */
    @Column(name = "YHSJB")
    private String yhsjb;
    /**
     * 契税满两年
     */
    @Column(name = "QSMLN")
    private String qsmln;
    /**
     * 上手购房契税金额
     */
    @Column(name = "SSGFQSJE")
    private Double ssgfqsje;
    /**
     * 上手物业维修基金金额
     */
    @Column(name = "SSWYWXJJJE")
    private Double sswywxjjje;
    /**
     * 上手交易类型
     */
    @Column(name = "SSJYLX")
    private String ssjylx;

    /**
     * 上手交易日期
     */
    @Column(name = "SSJYRQ")
    private Date ssjyrq;
    /**
     * 所得税征收标记
     */
    @Column(name = "SDSZSBJ")
    private String sdszsbj;
    /**
     * 所得税减免标记
     */
    @Column(name = "SDSJMBJ")
    private String sdsjmbj;
    /**
     * 所得税减免项目
     */
    @Column(name = "SDSJMXM")
    private String sdsjmxm;
    /**
     * 增值税税率
     */
    @Column(name = "ZZSSL")
    private String zzssl;
    /**
     * 中介机构名称
     */
    @Column(name = "ZJJGMC")
    private String zjjgmc;
    /**
     * 中介机构代码
     */
    @Column(name = "ZJJGDM")
    private String zjjgdm;
    /**
     * 交易编号
     */
    @Column(name = "JYBH")
    private String jybh;
    /**
     * 业务类型名称
     */
    @Column(name = "YWLXMC")
    private String ywlxmc;
    /**
     * 合同类型名称
     */
    @Column(name = "HTLXMC")
    private String htlxmc;
    /**
     * 房屋原值购置房价款
     */
    @Column(name = "YZFK")
    private Double yzfk;
    /**
     * 房屋原值契税
     */
    @Column(name = "YZQS")
    private Double yzqs;
    /**
     * 合理费用按规定缴纳的其他费用
     */
    @Column(name = "HLQT")
    private Double hlqt;
    /**
     * 公证费
     */
    @Column(name = "HLGZF")
    private Double hlgzf;
    /**
     * 住房装修费
     */
    @Column(name = "HLZX")
    private Double hlzx;
    /**
     * 房屋原值交易手续费
     */
    @Column(name = "YZJYSXF")
    private Double yzjysxf;
    /**
     * 房屋原值缴纳的其他税费
     */
    @Column(name = "YZQT")
    private Double yzqt;
    /**
     * 房屋原值印花税
     */
    @Column(name = "YZYHS")
    private Double yzyhs;
    /**
     * 转让过程中缴纳的其他税费
     */
    @Column(name = "ZRQT")
    private Double zrqt;
    /**
     * 转让住房过程中的税费、印花税
     */
    @Column(name = "ZRYHS")
    private Double zryhs;
    /**
     * 转让增值税
     */
    @Column(name = "ZRZZS")
    private Double zrzzs;

    public String getJyxxid() {
        return this.jyxxid;
    }

    public void setJyxxid(String jyxxid) {
        this.jyxxid = jyxxid;
    }

    public String getXmbh() {
        return this.xmbh;
    }

    public void setXmbh(String xmbh) {
        this.xmbh = xmbh;
    }

    public String getHtbh() {
        return this.htbh;
    }

    public void setHtbh(String htbh) {
        this.htbh = htbh;
    }

    public String getHtzt() {
        return this.htzt;
    }

    public void setHtzt(String htzt) {
        this.htzt = htzt;
    }

    public String getHtbah() {
        return this.htbah;
    }

    public void setHtbah(String htbah) {
        this.htbah = htbah;
    }

    public Double getJyje() {
        return this.jyje;
    }

    public void setJyje(Double jyje) {
        this.jyje = jyje;
    }

    public Double getDj() {
        return this.dj;
    }

    public void setDj(Double dj) {
        this.dj = dj;
    }

    public Date getHtdjsj() {
        return this.htdjsj;
    }

    public void setHtdjsj(Date htdjsj) {
        this.htdjsj = htdjsj;
    }

    public Date getHtbasj() {
        return this.htbasj;
    }

    public void setHtbasj(Date htbasj) {
        this.htbasj = htbasj;
    }

    public String getSjgsdq() {
        return this.sjgsdq;
    }

    public void setSjgsdq(String sjgsdq) {
        this.sjgsdq = sjgsdq;
    }

    public String getBz() {
        return this.bz;
    }

    public void setBz(String bz) {
        this.bz = bz;
    }

    public String getProid() {
        return this.proid;
    }

    public void setProid(String proid) {
        this.proid = proid;
    }

    public Double getHtje() {
        return this.htje;
    }

    public void setHtje(Double htje) {
        this.htje = htje;
    }

    public Double getSfje() {
        return this.sfje;
    }

    public void setSfje(Double sfje) {
        this.sfje = sfje;
    }

    public Double getDkje() {
        return this.dkje;
    }

    public void setDkje(Double dkje) {
        this.dkje = dkje;
    }

    public Double getJgje() {
        return this.jgje;
    }

    public void setJgje(Double jgje) {
        this.jgje = jgje;
    }

    public String getYhdm() {
        return this.yhdm;
    }

    public void setYhdm(String yhdm) {
        this.yhdm = yhdm;
    }

    public String getJgzhkhh() {
        return this.jgzhkhh;
    }

    public void setJgzhkhh(String jgzhkhh) {
        this.jgzhkhh = jgzhkhh;
    }

    public String getJgzhh() {
        return this.jgzhh;
    }

    public void setJgzhh(String jgzhh) {
        this.jgzhh = jgzhh;
    }

    public String getJgzhm() {
        return this.jgzhm;
    }

    public void setJgzhm(String jgzhm) {
        this.jgzhm = jgzhm;
    }

    public String getQszydx() {
        return this.qszydx;
    }

    public void setQszydx(String qszydx) {
        this.qszydx = qszydx;
    }

    public String getQszyfs() {
        return this.qszyfs;
    }

    public void setQszyfs(String qszyfs) {
        this.qszyfs = qszyfs;
    }

    public String getQszyyt() {
        return this.qszyyt;
    }

    public void setQszyyt(String qszyyt) {
        this.qszyyt = qszyyt;
    }

    public String getCjjgsfhs() {
        return this.cjjgsfhs;
    }

    public void setCjjgsfhs(String cjjgsfhs) {
        this.cjjgsfhs = cjjgsfhs;
    }

    public String getSfcezs() {
        return this.sfcezs;
    }

    public void setSfcezs(String sfcezs) {
        this.sfcezs = sfcezs;
    }

    public String getSfgyrdp() {
        return this.sfgyrdp;
    }

    public void setSfgyrdp(String sfgyrdp) {
        this.sfgyrdp = sfgyrdp;
    }

    public Double getSdskc() {
        return this.sdskc;
    }

    public void setSdskc(Double sdskc) {
        this.sdskc = sdskc;
    }

    public String getSbjysfszzr() {
        return this.sbjysfszzr;
    }

    public void setSbjysfszzr(String sbjysfszzr) {
        this.sbjysfszzr = sbjysfszzr;
    }

    public Double getJydkje() {
        return this.jydkje;
    }

    public void setJydkje(Double jydkje) {
        this.jydkje = jydkje;
    }

    public String getSkssyf() {
        return this.skssyf;
    }

    public void setSkssyf(String skssyf) {
        this.skssyf = skssyf;
    }

    public String getDjzclx() {
        return this.djzclx;
    }

    public void setDjzclx(String djzclx) {
        this.djzclx = djzclx;
    }

    public Double getSsjg() {
        return this.ssjg;
    }

    public void setSsjg(Double ssjg) {
        this.ssjg = ssjg;
    }

    public String getBdcxmbh() {
        return this.bdcxmbh;
    }

    public void setBdcxmbh(String bdcxmbh) {
        this.bdcxmbh = bdcxmbh;
    }

    public String getJylx() {
        return this.jylx;
    }

    public void setJylx(String jylx) {
        this.jylx = jylx;
    }

    public Double getBaje() {
        return this.baje;
    }

    public void setBaje(Double baje) {
        this.baje = baje;
    }

    public Date getScqdfwsj() {
        return this.scqdfwsj;
    }

    public void setScqdfwsj(Date scqdfwsj) {
        this.scqdfwsj = scqdfwsj;
    }

    public String getSfdstdsyj() {
        return this.sfdstdsyj;
    }

    public void setSfdstdsyj(String sfdstdsyj) {
        this.sfdstdsyj = sfdstdsyj;
    }

    public Date getFczfzsj() {
        return fczfzsj;
    }

    public void setFczfzsj(Date fczfzsj) {
        this.fczfzsj = fczfzsj;
    }

    public Date getGffpqdsj() {
        return gffpqdsj;
    }

    public void setGffpqdsj(Date gffpqdsj) {
        this.gffpqdsj = gffpqdsj;
    }

    public Date getGfqswcsj() {
        return gfqswcsj;
    }

    public void setGfqswcsj(Date gfqswcsj) {
        this.gfqswcsj = gfqswcsj;
    }

    public Double getBhzzsje() {
        return bhzzsje;
    }

    public void setBhzzsje(Double bhzzsje) {
        this.bhzzsje = bhzzsje;
    }

    public Double getZzsje() {
        return zzsje;
    }

    public void setZzsje(Double zzsje) {
        this.zzsje = zzsje;
    }

    public String getFkfs() {
        return fkfs;
    }

    public void setFkfs(String fkfs) {
        this.fkfs = fkfs;
    }

    public String getYhsjb() {
        return yhsjb;
    }

    public void setYhsjb(String yhsjb) {
        this.yhsjb = yhsjb;
    }

    public Double getHzzsje() {
        return hzzsje;
    }

    public void setHzzsje(Double hzzsje) {
        this.hzzsje = hzzsje;
    }

    public String getQsmln() {
        return qsmln;
    }

    public void setQsmln(String qsmln) {
        this.qsmln = qsmln;
    }

    public Double getSsgfqsje() {
        return ssgfqsje;
    }

    public void setSsgfqsje(Double ssgfqsje) {
        this.ssgfqsje = ssgfqsje;
    }

    public Double getSswywxjjje() {
        return sswywxjjje;
    }

    public void setSswywxjjje(Double sswywxjjje) {
        this.sswywxjjje = sswywxjjje;
    }

    public Date getSsjyrq() {
        return ssjyrq;
    }

    public void setSsjyrq(Date ssjyrq) {
        this.ssjyrq = ssjyrq;
    }

    public String getSdszsbj() {
        return sdszsbj;
    }

    public void setSdszsbj(String sdszsbj) {
        this.sdszsbj = sdszsbj;
    }

    public String getSsjylx() {
        return ssjylx;
    }

    public void setSsjylx(String ssjylx) {
        this.ssjylx = ssjylx;
    }

    public String getSdsjmbj() {
        return sdsjmbj;
    }

    public void setSdsjmbj(String sdsjmbj) {
        this.sdsjmbj = sdsjmbj;
    }

    public String getSdsjmxm() {
        return sdsjmxm;
    }

    public void setSdsjmxm(String sdsjmxm) {
        this.sdsjmxm = sdsjmxm;
    }

    public String getZzssl() {
        return zzssl;
    }

    public void setZzssl(String zzssl) {
        this.zzssl = zzssl;
    }

    public String getZjjgmc() {
        return zjjgmc;
    }

    public void setZjjgmc(String zjjgmc) {
        this.zjjgmc = zjjgmc;
    }

    public String getZjjgdm() {
        return zjjgdm;
    }

    public void setZjjgdm(String zjjgdm) {
        this.zjjgdm = zjjgdm;
    }

    public String getJybh() {
        return jybh;
    }

    public void setJybh(String jybh) {
        this.jybh = jybh;
    }

    public String getYwlxmc() {
        return ywlxmc;
    }

    public void setYwlxmc(String ywlxmc) {
        this.ywlxmc = ywlxmc;
    }

    public String getHtlxmc() {
        return htlxmc;
    }

    public void setHtlxmc(String htlxmc) {
        this.htlxmc = htlxmc;
    }

    public Double getYzyhs() {
        return yzyhs;
    }

    public void setYzyhs(Double yzyhs) {
        this.yzyhs = yzyhs;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Double getYzfk() {
        return yzfk;
    }

    public void setYzfk(Double yzfk) {
        this.yzfk = yzfk;
    }

    public Double getYzqs() {
        return yzqs;
    }

    public void setYzqs(Double yzqs) {
        this.yzqs = yzqs;
    }

    public Double getHlqt() {
        return hlqt;
    }

    public void setHlqt(Double hlqt) {
        this.hlqt = hlqt;
    }

    public Double getHlgzf() {
        return hlgzf;
    }

    public void setHlgzf(Double hlgzf) {
        this.hlgzf = hlgzf;
    }

    public Double getHlzx() {
        return hlzx;
    }

    public void setHlzx(Double hlzx) {
        this.hlzx = hlzx;
    }

    public Double getYzjysxf() {
        return yzjysxf;
    }

    public void setYzjysxf(Double yzjysxf) {
        this.yzjysxf = yzjysxf;
    }

    public Double getYzqt() {
        return yzqt;
    }

    public void setYzqt(Double yzqt) {
        this.yzqt = yzqt;
    }

    public Double getZrqt() {
        return zrqt;
    }

    public void setZrqt(Double zrqt) {
        this.zrqt = zrqt;
    }

    public Double getZryhs() {
        return zryhs;
    }

    public void setZryhs(Double zryhs) {
        this.zryhs = zryhs;
    }

    public Double getZrzzs() {
        return zrzzs;
    }

    public void setZrzzs(Double zrzzs) {
        this.zrzzs = zrzzs;
    }
}
