package cn.gtmap.realestate.etl.core.domian.ycsl;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Thu Aug 02 16:19:23 CST 2018.</p>
 *
 * @author huangzijian
 */

@Entity
@Table(name = "YCSL_XM")
public class YcslXmDo implements Serializable {


    /**
     * 主键
     */
    @Column(name = "PROID")
    @Id
    private String proid;

    /**
     * 流程id
     */
    @Column(name = "WIID")
    private String wiid;

    /**
     * 单位代码
     */
    @Column(name = "DWDM")
    private String dwdm;

    /**
     * 编号
     */
    @Column(name = "XMBH")
    private String xmbh;

    /**
     * 流水号
     */
    @Column(name = "LSH")
    private String lsh;

    /**
     * 年份
     */
    @Column(name = "NF")
    private String nf;

    /**
     * 项目创建人
     */
    @Column(name = "CJR")
    private String cjr;

    /**
     * 项目创建时间
     */
    @Column(name = "CJSJ")
    private Date cjsj;

    /**
     * 1：不动产2：过渡
     */
    @Column(name = "BDCXMLY")
    private String bdcxmly;

    /**
     * 行政区代码
     */
    @Column(name = "XZQDM")
    private String xzqdm;

    /**
     * 查询机构标识
     */
    @Column(name = "CXJGBS")
    private String cxjgbs;

    /**
     * 备注
     */
    @Column(name = "BZ")
    private String bz;

    /**
     * 登记原因
     */
    @Column(name = "DJYY")
    private String djyy;

    /**
     * 登记类型代码
     */
    @Column(name = "DJLX")
    private String djlx;

    /**
     * 登记类型名称
     */
    @Column(name = "DJLXMC")
    private String djlxmc;


    /**
     * 申请类型代码
     */
    @Column(name = "SQLXDM")
    private String sqlxdm;

    /**
     * 申请类型名称
     */
    @Column(name = "SQDJLXMC")
    private String sqdjlxmc;

    /**
     * 权利类型代码
     */
    @Column(name = "QLLX")
    private String qllx;

    /**
     * 权利类型名称
     */
    @Column(name = "QLLXMC")
    private String qllxmc;

    /**
     * 共有方式代码
     */
    @Column(name = "GYFS")
    private String gyfs;

    /**
     * 共有方式名称
     */
    @Column(name = "GYFSMC")
    private String gyfsmc;

    /**
     * 是否分别持证
     */
    @Column(name = "SFFBCZ")
    private String sffbcz;

    /**
     * 原房产证号
     */
    @Column(name = "YFCZH")
    private String yfczh;

    /**
     * 原土地证号
     */
    @Column(name = "YTDZH")
    private String ytdzh;

    /**
     * 原不动产权证号
     */
    @Column(name = "YBDCQZH")
    private String ybdcqzh;

    /**
     * 原不动产业务号
     */
    @Column(name = "YBDCYWH")
    private String ybdcywh;

    /**
     * 原房产业务号
     */
    @Column(name = "YFCYWH")
    private String yfcywh;

    /**
     * 原土地业务号
     */
    @Column(name = "YTDYWH")
    private String ytdywh;

    /**
     * 失败原因
     */
    @Column(name = "SBYY")
    private String sbyy;

    /**
     * 创建状态
     */
    @Column(name = "CJZT")
    private String cjzt;

    /**
     * 登记受理单编号
     */
    @Column(name = "DJSLDBH")
    private String djsldbh;

    /**
     * 业务编号
     */
    @Column(name = "YWBH")
    private Long ywbh;
    /**
     * 登记系统 项目id
     */
    @Column(name = "BDCXMID")
    private String bdcxmid;
    /**
     * 是否推送到登记系统（0或空代表未推送，1代表推送）
     */
    @Column(name = "SFTSDJ")
    private String sftsdj;

    /**
     * 项目创建人联系电话
     */
    @Column(name = "CJRLXDH")
    private String cjrlxdh;

    /**
     * 原不动产权证号简称
     */
    @Column(name = "YBDCQZHJC")
    private String ybdcqzhjc;

    /**
     * 是否房查
     */
    @Column(name = "SFFC")
    private String sffc;

    /**
     * 登记子项
     */
    @Column(name = "DJZX")
    private String djzx;

    public String getProid() {
        return proid;
    }

    public void setProid(String proid) {
        this.proid = proid;
    }

    public String getWiid() {
        return wiid;
    }

    public void setWiid(String wiid) {
        this.wiid = wiid;
    }

    public String getDwdm() {
        return dwdm;
    }

    public void setDwdm(String dwdm) {
        this.dwdm = dwdm;
    }

    public String getXmbh() {
        return xmbh;
    }

    public void setXmbh(String xmbh) {
        this.xmbh = xmbh;
    }

    public String getLsh() {
        return lsh;
    }

    public void setLsh(String lsh) {
        this.lsh = lsh;
    }

    public String getNf() {
        return nf;
    }

    public void setNf(String nf) {
        this.nf = nf;
    }

    public String getCjr() {
        return cjr;
    }

    public void setCjr(String cjr) {
        this.cjr = cjr;
    }

    public Date getCjsj() {
        return cjsj;
    }

    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    public String getBdcxmly() {
        return bdcxmly;
    }

    public void setBdcxmly(String bdcxmly) {
        this.bdcxmly = bdcxmly;
    }

    public String getXzqdm() {
        return xzqdm;
    }

    public void setXzqdm(String xzqdm) {
        this.xzqdm = xzqdm;
    }

    public String getCxjgbs() {
        return cxjgbs;
    }

    public void setCxjgbs(String cxjgbs) {
        this.cxjgbs = cxjgbs;
    }

    public String getBz() {
        return bz;
    }

    public void setBz(String bz) {
        this.bz = bz;
    }

    public String getDjyy() {
        return djyy;
    }

    public void setDjyy(String djyy) {
        this.djyy = djyy;
    }

    public String getDjlx() {
        return djlx;
    }

    public void setDjlx(String djlx) {
        this.djlx = djlx;
    }

    public String getDjlxmc() {
        return djlxmc;
    }

    public void setDjlxmc(String djlxmc) {
        this.djlxmc = djlxmc;
    }

    public String getSqlxdm() {
        return sqlxdm;
    }

    public void setSqlxdm(String sqlxdm) {
        this.sqlxdm = sqlxdm;
    }

    public String getSqdjlxmc() {
        return sqdjlxmc;
    }

    public void setSqdjlxmc(String sqdjlxmc) {
        this.sqdjlxmc = sqdjlxmc;
    }

    public String getQllx() {
        return qllx;
    }

    public void setQllx(String qllx) {
        this.qllx = qllx;
    }

    public String getQllxmc() {
        return qllxmc;
    }

    public void setQllxmc(String qllxmc) {
        this.qllxmc = qllxmc;
    }

    public String getGyfs() {
        return gyfs;
    }

    public void setGyfs(String gyfs) {
        this.gyfs = gyfs;
    }

    public String getGyfsmc() {
        return gyfsmc;
    }

    public void setGyfsmc(String gyfsmc) {
        this.gyfsmc = gyfsmc;
    }

    public String getSffbcz() {
        return sffbcz;
    }

    public void setSffbcz(String sffbcz) {
        this.sffbcz = sffbcz;
    }

    public String getYfczh() {
        return yfczh;
    }

    public void setYfczh(String yfczh) {
        this.yfczh = yfczh;
    }

    public String getYtdzh() {
        return ytdzh;
    }

    public void setYtdzh(String ytdzh) {
        this.ytdzh = ytdzh;
    }

    public String getYbdcqzh() {
        return ybdcqzh;
    }

    public void setYbdcqzh(String ybdcqzh) {
        this.ybdcqzh = ybdcqzh;
    }

    public String getYbdcywh() {
        return ybdcywh;
    }

    public void setYbdcywh(String ybdcywh) {
        this.ybdcywh = ybdcywh;
    }

    public String getYfcywh() {
        return yfcywh;
    }

    public void setYfcywh(String yfcywh) {
        this.yfcywh = yfcywh;
    }

    public String getYtdywh() {
        return ytdywh;
    }

    public void setYtdywh(String ytdywh) {
        this.ytdywh = ytdywh;
    }


    public String getSbyy() {
        return sbyy;
    }

    public void setSbyy(String sbyy) {
        this.sbyy = sbyy;
    }

    public String getCjzt() {
        return cjzt;
    }

    public void setCjzt(String cjzt) {
        this.cjzt = cjzt;
    }

    public String getDjsldbh() {
        return djsldbh;
    }

    public void setDjsldbh(String djsldbh) {
        this.djsldbh = djsldbh;
    }

    public Long getYwbh() {
        return ywbh;
    }

    public void setYwbh(Long ywbh) {
        this.ywbh = ywbh;
    }

    public String getBdcxmid() {
        return bdcxmid;
    }

    public void setBdcxmid(String bdcxmid) {
        this.bdcxmid = bdcxmid;
    }

    public String getSftsdj() {
        return sftsdj;
    }

    public void setSftsdj(String sftsdj) {
        this.sftsdj = sftsdj;
    }

    public String getCjrlxdh() {
        return cjrlxdh;
    }

    public void setCjrlxdh(String cjrlxdh) {
        this.cjrlxdh = cjrlxdh;
    }

    public String getYbdcqzhjc() {
        return ybdcqzhjc;
    }

    public void setYbdcqzhjc(String ybdcqzhjc) {
        this.ybdcqzhjc = ybdcqzhjc;
    }

    public String getSffc() {
        return sffc;
    }

    public void setSffc(String sffc) {
        this.sffc = sffc;
    }

    public String getDjzx() {
        return djzx;
    }

    public void setDjzx(String djzx) {
        this.djzx = djzx;
    }
}
